import { chromium } from '@playwright/test';
import fs from 'node:fs';
import { chapters } from '../src/content.ts';
const baseURL=process.env.ATLAS_TEST_URL||'http://127.0.0.1:4173';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1050},deviceScaleFactor:1});
const errors=[];
page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url())});
page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
await page.goto(baseURL);
await page.getByRole('heading',{name:'推理引擎的全景地图',exact:true}).waitFor();
await page.screenshot({path:'tests/screenshots/overview-desktop.png',fullPage:false});
for(const c of chapters){await page.goto(`${baseURL}/#/${c.id}`);await page.getByRole('heading',{name:c.title,exact:true}).waitFor();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2);if(overflow)throw Error('Desktop overflow '+c.id);}
await page.goto(`${baseURL}/#/sparse`);
const modelGroup=page.locator('.nav-group').filter({has:page.getByRole('heading',{name:'模型深潜',exact:true})});
if(await modelGroup.locator('.nav-item').count()!==2)throw Error('Model navigation must contain exactly two models');
if(!(await modelGroup.locator('.nav-item.active').innerText()).includes('DeepSeek V4'))throw Error('Sparse page lost model parent');
await page.getByRole('navigation',{name:'DeepSeek V4 内容'}).getByRole('button',{name:'架构总览',exact:true}).click();
await page.getByRole('heading',{name:'DeepSeek V4：压缩历史与多流残差',exact:true}).waitFor();
await page.screenshot({path:'tests/screenshots/model-navigation-desktop.png'});
await page.goto(`${baseURL}/#/kimi`);
await page.getByRole('button',{name:'第 93 层 MLA',exact:true}).click();
await page.getByText('LAYER 93',{exact:true}).waitFor();
await page.locator('.source-link').filter({hasText:'KimiK3DecoderLayer'}).first().click();
await page.locator('.code-row.highlight').first().waitFor();
if(!await page.locator('.code-row.highlight').first().innerText().then(t=>t.includes('class KimiK3DecoderLayer')))throw Error('Wrong code target');
await page.screenshot({path:'tests/screenshots/code-desktop.png'});
await page.getByLabel('在当前源码内搜索').fill('forward');
await page.getByRole('button',{name:'下一个代码匹配',exact:true}).click();
await page.getByRole('button',{name:'关闭源码',exact:true}).click();
await page.getByRole('button',{name:'搜索知识与源码'}).click();
await page.getByLabel('全站搜索').fill('MambaSpec');
await page.locator('.search-result').filter({hasText:'MambaSpec'}).first().click();
await page.locator('.code-reader').waitFor();
await page.getByRole('button',{name:'关闭源码',exact:true}).click();
await page.goto(`${baseURL}/#/scheduler`);
await page.getByRole('button',{name:'推进一轮',exact:true}).click();
if(await page.locator('.schedule-row').count()!==3)throw Error('Scheduler did not advance');
await page.goto(`${baseURL}/#/deepseek`);
await page.getByLabel('Checkpoint').selectOption('pro');
if(await page.locator('.layer-tile').count()!==61)throw Error('Wrong Pro layer count');
await page.screenshot({path:'tests/screenshots/deepseek-desktop.png'});
await page.goto(`${baseURL}/#/kda`);
await page.getByRole('button',{name:'切换深色主题'}).click();
await page.screenshot({path:'tests/screenshots/memory-dark.png'});
for(const width of [1024,736,360]){
 await page.setViewportSize({width,height:900});
 for(const c of chapters){await page.goto(`${baseURL}/#/${c.id}`);await page.getByRole('heading',{name:c.title,exact:true}).waitFor();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2);if(overflow)throw Error(`Overflow ${width} ${c.id}`);}
 await page.goto(`${baseURL}/#/overview`);
 await page.screenshot({path:`tests/screenshots/overview-${width}-dark.png`});
}
await page.getByRole('button',{name:'切换浅色主题'}).click();
await page.screenshot({path:'tests/screenshots/overview-mobile.png'});
await page.getByRole('button',{name:'打开目录',exact:true}).click();
await page.locator('.nav-item').filter({hasText:'Kimi K3'}).click();
await page.getByRole('navigation',{name:'Kimi K3 内容'}).getByRole('button',{name:'KDA 与状态缓存',exact:true}).click();
await page.getByRole('heading',{name:'KDA：递归状态如何进入推理框架',exact:true}).waitFor();
await page.locator('.source-link').first().click();
await page.locator('.code-row.highlight').first().waitFor();
await page.screenshot({path:'tests/screenshots/code-mobile.png'});
await page.getByRole('button',{name:'关闭源码',exact:true}).click();
if(errors.length)throw Error(errors.join('\n'));
console.log(JSON.stringify({chapters:chapters.length,viewports:[1440,1024,736,360],errors,checks:['all routes','source line jump','file search','global symbol search','scheduler step','model variants','theme','mobile navigation']}));
await browser.close();
