import {useEffect,useState,lazy,Suspense} from 'react';
import {Search,Sun,Moon,ArrowRight,ArrowLeft,PanelLeftClose,PanelLeftOpen,Check,Bookmark,BookOpen,Network,ChevronRight} from 'lucide-react';
import {topics,topicGroups,guideFor,parseRoute,routeURL,views,type View} from './curriculum';
import type {Framework} from './curriculumTypes';
import {sourceIndex,resolveRef,repoName} from './data';
import {StudyPage} from './StudyPage';
import './study.css';
const CodeReader=lazy(()=>import('./CodeReader').then(m=>({default:m.CodeReader})));
const SearchDialog=lazy(()=>import('./SearchDialog').then(m=>({default:m.SearchDialog})));
function locationState(){const route=parseRoute(location.hash);try{if(route.code){const repo=resolveRef(route.code).file.repo;if(repo==='sglang'||repo==='vllm')route.engine=repo}}catch{route.code=null}return route}
function saved<T>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)??'null')??fallback}catch{return fallback}}
export default function App(){
 const [route,setRoute]=useState(locationState),[theme,setTheme]=useState<'light'|'dark'>(()=>saved('atlas-theme','light')),[sidebar,setSidebar]=useState(false),[search,setSearch]=useState<string|null>(null),[read,setRead]=useState<string[]>(()=>saved('atlas-read-v2',[])),[bookmarks,setBookmarks]=useState<string[]>(()=>saved('atlas-bookmarks-v2',[]));
 const topic=topics.find(t=>t.id===route.topic)!,guide=guideFor(route.engine,route.topic),parent=topic.parent?topics.find(t=>t.id===topic.parent):undefined;
 const family=topics.filter(t=>t.id===(parent?.id??topic.id)||t.parent===(parent?.id??topic.id)),index=topics.indexOf(topic),key=`${route.engine}:${topic.id}`;
 const engineName=repoName(route.engine),readCount=read.filter(k=>k.startsWith(route.engine+':')).length;
 useEffect(()=>{const fn=()=>setRoute(locationState());window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn)},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('atlas-theme',JSON.stringify(theme))},[theme]);
 useEffect(()=>{document.title=`${engineName} · ${topic.title} · 推理架构图谱`;window.scrollTo({top:0,behavior:'instant'});setSidebar(false)},[route.engine,route.topic,topic.title,engineName]);
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();setSearch('')}if(e.key==='Escape'&&search===null){if(route.code)closeCode();else setSidebar(false)}};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[route,search]);
 function navigate(id:string,view:View=id==='cache'?'lab':'map',engine:Framework=route.engine,code:string|null=null){const next={topic:id,view,engine,code};location.hash=routeURL(engine,id,view,code);setRoute(next)}
 function open(ref:string){const repo=resolveRef(ref).file.repo;navigate(topic.id,route.view,repo==='sglang'||repo==='vllm'?repo:route.engine,ref)}
 function closeCode(){navigate(topic.id,route.view)}
 function toggle(list:string[],set:(v:string[])=>void,storage:string){const next=list.includes(key)?list.filter(x=>x!==key):[...list,key];set(next);localStorage.setItem(storage,JSON.stringify(next))}
 const sourceCount=Object.values(sourceIndex.files).filter(f=>f.repo===route.engine).length;
 return <><a href="#article" className="skip-link" onClick={e=>{e.preventDefault();document.getElementById('article')?.focus()}}>跳到正文</a><header className="topbar"><div className="brand"><button className="icon-button menu-button" aria-label={sidebar?'关闭目录':'打开目录'} onClick={()=>setSidebar(!sidebar)}>{sidebar?<PanelLeftClose size={21}/>:<PanelLeftOpen size={21}/>}</button><button className="brand-link" onClick={()=>navigate('overview')}><span className="brand-icon"><Network size={20}/></span><span>推理架构图谱<small>INFERENCE ATLAS</small></span></button></div><div className="top-actions"><span className="current-track">{engineName}<span>/</span>{topic.title}</span><button className="search-trigger" onClick={()=>setSearch('')}><Search size={16}/><span>搜索 {engineName} 与源码</span><kbd>⌘ K</kbd></button><button className="icon-button" aria-label={theme==='light'?'切换深色主题':'切换浅色主题'} onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={18}/>:<Sun size={18}/>}</button></div></header>
 {sidebar&&<button className="sidebar-backdrop" aria-label="收起目录" onClick={()=>setSidebar(false)}/>}
 <aside className={`sidebar ${sidebar?'is-open':''}`}><div className="sidebar-intro"><span className="eyebrow">CURRENT FRAMEWORK</span><strong>{engineName}{route.engine==='vllm'&&<small>V1</small>}</strong><p>{topics.length} 个专题 · {sourceCount} 份源码</p></div><nav aria-label="专题目录">{topicGroups.map((group,groupIndex)=><div className="nav-group" key={group}><h2><span>0{groupIndex+1}</span>{group}</h2>{topics.filter(t=>t.group===group&&!t.parent).map(t=><div key={t.id}><button className={`nav-item ${t.id===(parent?.id??topic.id)?'active':''}`} aria-current={t.id===topic.id?'page':undefined} onClick={()=>navigate(t.id)}><span>{t.title}</span>{read.includes(`${route.engine}:${t.id}`)?<Check size={12}/>:topics.some(c=>c.parent===t.id)?<ChevronRight size={13}/>:null}</button>{(t.id===(parent?.id??topic.id))&&topics.some(c=>c.parent===t.id)&&<div className="nav-children">{topics.filter(c=>c.parent===t.id).map(child=><button key={child.id} className={child.id===topic.id?'active':''} aria-current={child.id===topic.id?'page':undefined} onClick={()=>navigate(child.id)}>{child.title}</button>)}</div>}</div>)}</div>)}</nav><div className="reading-progress"><div><span>{engineName} 阅读进度</span><strong>{readCount} / {topics.length}</strong></div><div className="progress-track"><div style={{width:`${readCount/topics.length*100}%`}}/></div><small>两套框架分别记录 · 仅本机保存</small></div></aside>
 <main className={`main-content study-main ${route.code?'with-code':''}`} id="article" tabIndex={-1} data-engine={route.engine}>
 <nav className="framework-switch" aria-label="切换框架">{(['sglang','vllm'] as Framework[]).map(e=><button key={e} aria-current={e===route.engine?'page':undefined} onClick={()=>navigate(topic.id,route.view,e)}><span className={`framework-mark ${e}`}>{e==='sglang'?'S':'V'}</span><span><strong>{repoName(e)}</strong><small>{e==='sglang'?'Scheduler · Radix · ForwardBatch':'V1 · BlockPool · SchedulerOutput'}</small></span>{e===route.engine&&<Check size={16}/>}</button>)}</nav>
 <div className="article-top"><span>{engineName}<ChevronRight size={12}/>{topic.group}{parent&&<><ChevronRight size={12}/>{parent.title}</>}</span><div><button className={`icon-button ${bookmarks.includes(key)?'bookmarked':''}`} aria-label={bookmarks.includes(key)?'取消收藏专题':'收藏专题'} aria-pressed={bookmarks.includes(key)} onClick={()=>toggle(bookmarks,setBookmarks,'atlas-bookmarks-v2')}><Bookmark size={17}/></button><button className="button small-button" onClick={()=>toggle(read,setRead,'atlas-read-v2')}>{read.includes(key)?<Check size={14}/>:<BookOpen size={14}/>}<span>{read.includes(key)?'已读':'标记已读'}</span></button></div></div>
 <div className="study-hero"><span className="eyebrow">{String(index+1).padStart(2,'0')} / {topic.group}</span><h1>{topic.title}</h1><div className="central-question"><span>这一页要回答</span><h2>{guide.question}</h2><p>{guide.answer}</p></div></div>
 {family.length>1&&<nav className="model-sections" aria-label={`${parent?.title??topic.title} 内容`}><div>{family.map(t=><button key={t.id} aria-current={t.id===topic.id?'page':undefined} onClick={()=>navigate(t.id)}>{t.parent?t.title:'架构总览'}</button>)}</div></nav>}
 <nav className="study-tabs" role="tablist" aria-label="本页层次">{views.filter(v=>v.id!=='lab'||topic.lab).map(v=><button key={v.id} role="tab" id={`tab-${v.id}`} aria-controls={`panel-${v.id}`} aria-selected={route.view===v.id} onClick={()=>navigate(topic.id,v.id)}>{v.id==='lab'&&topic.id==='sources'?'文件索引':v.title}</button>)}</nav>
 <StudyPage key={`${route.engine}:${topic.id}`} engine={route.engine} topic={topic} view={route.view} open={open} go={navigate} changeView={view=>navigate(topic.id,view)} theme={theme}/>
 <div className="page-navigation">{index>0?<button onClick={()=>navigate(topics[index-1].id)}><ArrowLeft size={17}/><span><small>{engineName} · 上一专题</small>{topics[index-1].title}</span></button>:<span/>}{index<topics.length-1&&<button onClick={()=>navigate(topics[index+1].id)}><span><small>{engineName} · 下一专题</small>{topics[index+1].title}</span><ArrowRight size={17}/></button>}</div><footer><span>{engineName} · 固定源码 {sourceIndex.repos[route.engine].sha.slice(0,8)}</span><button onClick={()=>navigate('sources')}>查看证据与版本<ChevronRight size={12}/></button></footer>
 </main><Suspense fallback={<div className="loading-toast">正在打开…</div>}>{route.code&&<CodeReader reference={route.code} open={open} close={closeCode} searchSymbol={setSearch} engine={route.engine}/ >}{search!==null&&<SearchDialog initial={search} close={()=>setSearch(null)} go={id=>navigate(id)} open={open} engine={route.engine}/>}</Suspense></>
}
