import {useEffect,useState,lazy,Suspense} from 'react';
import {BookOpen,Search,Sun,Moon,ArrowRight,ArrowLeft,PanelLeftClose,PanelLeftOpen,Check,Bookmark,ExternalLink,Code2,Network,ChevronRight,FileCheck2} from 'lucide-react';
import {chapters,groups,frameworkLinks,familyForChapter,navigationChapters} from './content';
import {sourceIndex,resolveRef,type Engine} from './data';
import {References} from './References';
import {Lab} from './Labs';
const CodeReader=lazy(()=>import('./CodeReader').then(m=>({default:m.CodeReader})));
const SearchDialog=lazy(()=>import('./SearchDialog').then(m=>({default:m.SearchDialog})));
function locationState(){const hash=location.hash.replace(/^#\/?/,'');const [path,params]=hash.split('?');const id=chapters.some(c=>c.id===path)?path:'overview';let ref=new URLSearchParams(params).get('code');try{if(ref)resolveRef(ref)}catch{ref=null}return {id,ref}}
function saved<T>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)??'null')??fallback}catch{return fallback}}
export default function App(){
 const [route,setRoute]=useState(locationState),[engine,setEngine]=useState<Engine>('both'),[theme,setTheme]=useState<'light'|'dark'>(()=>saved('atlas-theme','light')),[sidebar,setSidebar]=useState(false),[search,setSearch]=useState<string|null>(null),[read,setRead]=useState<string[]>(()=>saved('atlas-read',[])),[bookmarks,setBookmarks]=useState<string[]>(()=>saved('atlas-bookmarks',[]));
 const chapter=chapters.find(c=>c.id===route.id)!,index=chapters.indexOf(chapter);
 const model=familyForChapter(chapter.id),navigationId=model?.id??chapter.id,navigationIndex=navigationChapters.findIndex(c=>c.id===navigationId);
 useEffect(()=>{const fn=()=>setRoute(locationState());window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn)},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('atlas-theme',JSON.stringify(theme))},[theme]);
 useEffect(()=>{document.title=`${chapter.title} · 推理架构图谱`;window.scrollTo({top:0,behavior:'instant'});setSidebar(false)},[chapter.id,chapter.title]);
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();setSearch('')}if(e.key==='Escape'&&search===null){if(route.ref)closeCode();else setSidebar(false)}};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[route,search]);
 function navigate(id:string,ref:string|null=null){const hash=`/${id}${ref?'?code='+encodeURIComponent(ref):''}`;location.hash=hash;setRoute({id,ref})}
 function open(ref:string){resolveRef(ref);navigate(route.id,ref)}
 function closeCode(){navigate(route.id)}
 function toggleList(list:string[],set:(v:string[])=>void,key:string){const next=list.includes(chapter.id)?list.filter(x=>x!==chapter.id):[...list,chapter.id];set(next);localStorage.setItem(key,JSON.stringify(next))}
 const cacheEngine:Engine|null=chapter.id==='cache'?'sglang':chapter.id==='cache-vllm'?'vllm':null;
 const evidenceEngine=cacheEngine??engine;
 const totalSymbols=Object.values(sourceIndex.files).reduce((n,f)=>n+f.symbols.length,0);
 return <><a href="#article" className="skip-link" onClick={e=>{e.preventDefault();document.getElementById('article')?.scrollIntoView()}}>跳到正文</a><header className="topbar"><div className="brand"><button className="icon-button menu-button" aria-label={sidebar?'关闭目录':'打开目录'} onClick={()=>setSidebar(!sidebar)}>{sidebar?<PanelLeftClose size={21}/>:<PanelLeftOpen size={21}/>}</button><button className="brand-link" onClick={()=>navigate('overview')}><span className="brand-icon"><Network size={20}/></span><span>推理架构图谱<small>INFERENCE ATLAS</small></span></button></div><div className="top-actions"><button className="search-trigger" onClick={()=>setSearch('')}><Search size={16}/><span>搜索知识与源码</span><kbd>⌘ K</kbd></button><span className="version-tag"><i/>2026.09.06</span><button className="icon-button" aria-label={theme==='light'?'切换深色主题':'切换浅色主题'} onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={18}/>:<Sun size={18}/>}</button></div></header>
 {sidebar&&<button className="sidebar-backdrop" aria-label="收起目录" onClick={()=>setSidebar(false)}/>}
 <aside className={`sidebar ${sidebar?'is-open':''}`}><div className="sidebar-intro"><span className="eyebrow">SOURCE-DRIVEN LEARNING</span><p>理解设计，再进入代码。</p></div><nav aria-label="专题目录">{groups.map(group=><div className="nav-group" key={group}><h2>{group}</h2>{navigationChapters.filter(c=>c.group===group).map(c=><button key={c.id} className={c.id===navigationId?'nav-item active':'nav-item'} aria-current={c.id===navigationId?'page':undefined} onClick={()=>navigate(c.id)}><span className="nav-number">{String(navigationChapters.indexOf(c)+1).padStart(2,'0')}</span><span>{c.title.split('：')[0]}</span>{(familyForChapter(c.id)?.sections.map(section=>section.id)??[c.id]).every(id=>read.includes(id))?<Check size={13}/>: (familyForChapter(c.id)?.sections.map(section=>section.id)??[c.id]).some(id=>bookmarks.includes(id))?<Bookmark size={12}/>:null}</button>)}</div>)}</nav><div className="reading-progress"><div><span>已读专题</span><strong>{read.length} / {chapters.length}</strong></div><div className="progress-track"><div style={{width:`${read.length/chapters.length*100}%`}}/></div><small>阅读记录仅保存在本机</small></div></aside>
 <main className={`main-content ${route.ref?'with-code':''}`} id="article"><div className="article-top"><span>{chapter.group}<ChevronRight size={13}/>{model&&<><span>{model.title}</span><ChevronRight size={13}/></>}<span>{String(navigationIndex+1).padStart(2,'0')} / {navigationChapters.length}</span></span><div><button className={`icon-button ${bookmarks.includes(chapter.id)?'bookmarked':''}`} aria-label={bookmarks.includes(chapter.id)?'取消收藏专题':'收藏专题'} aria-pressed={bookmarks.includes(chapter.id)} onClick={()=>toggleList(bookmarks,setBookmarks,'atlas-bookmarks')}><Bookmark size={17}/></button><button className="button small-button" onClick={()=>toggleList(read,setRead,'atlas-read')}>{read.includes(chapter.id)?<Check size={14}/>:<BookOpen size={14}/>}<span>{read.includes(chapter.id)?'已读':'标记已读'}</span></button></div></div>
 {model&&<nav className="model-sections" aria-label={`${model.title} 内容`}><span className="model-sections-label">{model.title}</span><div>{model.sections.map(section=><button key={section.id} aria-current={section.id===chapter.id?'page':undefined} onClick={()=>navigate(section.id)}>{section.title}</button>)}</div></nav>}
 <div className="hero"><div className="hero-eyebrow"><span>SGLANG</span><span className="cross">×</span><span>VLLM</span><i/><span>源码深度解析</span></div><h1>{chapter.title}</h1><p className="subtitle">{chapter.subtitle}</p><p className="intro">{chapter.intro}</p><div className="tag-row">{chapter.tags.map(t=><span key={t}>{t}</span>)}</div></div>
 {chapter.id==='overview'&&<div className="overview-facts"><div><strong>{chapters.length}</strong><span>系统与模型专题</span></div><div><strong>{Object.keys(sourceIndex.files).length}</strong><span>源码及测试快照</span></div><div><strong>{totalSymbols.toLocaleString()}</strong><span>可跳转类与函数</span></div><div><strong>02</strong><span>指定模型深潜</span></div></div>}
 <div className="evidence-toolbar"><div><FileCheck2 size={16}/><span>源码证据视角</span></div>{cacheEngine?<strong className="cache-engine-label">{cacheEngine==='sglang'?'SGLang 实现':'vLLM V1 实现'}</strong>:<div className="segmented compact" aria-label="选择源码框架">{(['both','sglang','vllm'] as Engine[]).map(e=><button key={e} aria-pressed={engine===e} onClick={()=>setEngine(e)}>{e==='both'?'双框架':e==='sglang'?'SGLang':'vLLM'}</button>)}</div>}<small>{cacheEngine?'上方切换框架；图与源码按各自结构展开':'切换关系图与引用；对照分析始终保留'}</small></div>
 {chapter.lab&&<Lab kind={chapter.lab} open={open} engine={evidenceEngine} go={id=>navigate(id)} theme={theme}/>}
 {chapter.compare&&<div className="comparison-wrap"><table className="comparison"><thead><tr><th>责任</th><th><i className="repo-dot sglang"/> SGLang</th><th><i className="repo-dot vllm"/> vLLM</th></tr></thead><tbody>{chapter.compare.map(r=><tr key={r[0]}>{r.map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table></div>}
 <div className="section-outline"><span>本节阅读</span>{chapter.sections.map((s,i)=><a key={s.title} href={`#section-${i}`} onClick={e=>{e.preventDefault();document.getElementById(`section-${i}`)?.scrollIntoView({behavior:'smooth',block:'start'})}}>{s.title}</a>)}</div>
 {chapter.sections.map((section,i)=><section className="analysis-section" key={section.title} id={`section-${i}`}><div className="section-heading"><span>{String(i+1).padStart(2,'0')}</span><h2>{section.title}</h2></div>{section.body.map((p,j)=><p key={j}>{p}</p>)}<div className="reasoning-pair"><div><span className="reason-label"><GitIcon/>设计原理</span><p>{section.principle}</p></div><div><span className="reason-label tradeoff">代价与边界</span><p>{section.tradeoff}</p></div></div><div className="evidence-caption"><Code2 size={13}/>对应实现 · 点击定位</div><References refs={section.refs} open={open} engine={evidenceEngine}/></section>)}
 {chapter.id==='sources'&&<div className="external-sources"><h3>官方网页框架资料</h3>{frameworkLinks.map(l=><a key={l.url} href={l.url} target="_blank" rel="noreferrer">{l.name}<ExternalLink size={14}/></a>)}<h3>固定源码基线</h3>{Object.entries(sourceIndex.repos).map(([name,r])=><a key={name} href={`https://github.com/${r.origin}/commit/${r.sha}`} target="_blank" rel="noreferrer">{name}<code>{r.sha}</code><ExternalLink size={14}/></a>)}</div>}
 <div className="related"><span className="eyebrow">继续建立连接</span><div>{chapter.related.map(id=>{const c=chapters.find(c=>c.id===id)!;return <button key={id} onClick={()=>navigate(id)}>{c.title.split('：')[0]}<ArrowRight size={15}/></button>})}</div></div><div className="page-navigation">{index>0?<button onClick={()=>navigate(chapters[index-1].id)}><ArrowLeft size={17}/><span><small>上一节</small>{chapters[index-1].title.split('：')[0]}</span></button>:<span/>}{index<chapters.length-1&&<button onClick={()=>navigate(chapters[index+1].id)}><span><small>下一节</small>{chapters[index+1].title.split('：')[0]}</span><ArrowRight size={17}/></button>}</div><footer><span>以实现为证据，以原理连接系统。</span><span>SGLang {sourceIndex.repos.sglang.sha.slice(0,8)} · vLLM {sourceIndex.repos.vllm.sha.slice(0,8)}</span></footer></main>
 <Suspense fallback={<div className="loading-toast">正在打开…</div>}>{route.ref&&<CodeReader reference={route.ref} open={open} close={closeCode} searchSymbol={setSearch}/ >}{search!==null&&<SearchDialog initial={search} close={()=>setSearch(null)} go={id=>navigate(id)} open={open}/>}</Suspense></>
}
function GitIcon(){return <span className="principle-dot"/>}
