import type {Chapter, Section} from './content.ts';
const s=(title:string,body:string[],principle:string,tradeoff:string,refs:string[]):Section=>({title,body,principle,tradeoff,refs});
export const cacheChapters:Chapter[]=[
{id:'cache',group:'核心机制',title:'KV cache：SGLang 的 Radix Tree',subtitle:'压缩路径 → KV 槽位 → 请求映射 → 路径锁与叶子淘汰',intro:'先沿 SGLang 的经典 RadixCache 读清一条完整实现链。树索引 token 前缀，节点保存已计算 KV 的位置；请求通过这些位置访问内存池。分页负责分配，压缩前缀树负责查找，两层职责可以同时存在。',tags:['SGLang','TreeNode','RadixKey','lock_ref'],lab:'cache',related:['cache-vllm','hybrid','kda','sparse'],sections:[
s('TreeNode：一条边容纳一段 token',['RadixKey.token_ids 保存 token 序列；TreeNode.key 表示当前压缩段，children 按下一段的首 token 或首 page 组织，parent 指向父节点。根是空 key/value 的哨兵，lock_ref=1。一段没有分叉的连续路径可以存成一个节点，即使它横跨多个 page。','TreeNode.value 是 torch.Tensor，元素是 KV 内存位置索引，不是 K/V 向量。示例 key=[11,12,13,14] 与 value=[40,41,70,71] 一一对应；物理槽不要求连续。hash_value、event_hash_value 用于相应存储/事件路径，因此“采用树”不代表实现里没有哈希。'],'压缩单分支路径减少 Python 节点与遍历开销；在出现真正的分叉时才细分节点。','树节点、token、内存 page 是三种单位。把每个方框都画成一个物理 KV block，会掩盖 key/value 切片和分裂的语义。',['sg.radix#RadixKey','sg.radix#TreeNode','sg.radix#RadixCache.reset']),
s('match_prefix：查找本身也会分裂树',['match_prefix 先处理 page 对齐，再沿 children 比较 key。A 的六个 token 原本是一个压缩段；B 在第 5 个 token 分叉，_split_node 会把公共四个 token 提为新父节点，原节点保留 A 的尾段。','分裂需要更新 parent、children、key、value，以及锁和哈希元数据。这里 clone 的是 value 的索引切片，KV payload 仍在原内存槽，未为共享前缀复制一份 K/V。','匹配结果拼接沿途 value，返回 device_indices 和 last_device_node 等。last_node 是保护路径的锚点，位置数组才是后续 attention 真正需要的寻址依据。'],'将内容匹配转为可直接复用的物理位置，省去共同前缀的 prefill 与重复 KV 存储。','这是会维护树结构的查询；不能把 match_prefix 想成永远只读。可复用边界还取决于 page size 和缓存实现。',['sg.radix#RadixCache.match_prefix','sg.radix#RadixCache._match_prefix_helper','sg.radix#RadixCache._split_node']),
s('从树到 GPU：三层数据结构如何接起来',['Req.prefix_indices 持有匹配位置，Req.last_node 指向匹配节点。ReqToTokenPool.req_to_token 是按请求槽、逻辑 token 位置索引的 GPU int32 表；表里的值仍是 KV 槽号。','准备 extend 时，请求表把公共前缀位置与新分配位置接在一起。模型通过批次 metadata / out_cache_loc 读取历史、写入新位置；实际数据由 MHATokenToKVPool、MLATokenToKVPool 等按层持有。','因此“共享前缀”可以表现为两个请求的表项指向相同槽；它们的新后缀分配到不同槽。树不是模型直接读取的一棵 GPU 指针树。'],'把 CPU 内容索引与 GPU 批量寻址分开，使灵活的前缀管理不会侵入每次 attention 内循环。','不同后端和 MLA 布局并不都保存完整展开的多头 K/V；槽号是抽象地址，具体张量布局要继续追到 pool。',['sg.batch#Req','sg.batch#ScheduleBatch.prepare_for_extend','sg.pool#ReqToTokenPool','sg.pool#MHATokenToKVPool','sg.pool#MLATokenToKVPool']),
s('lock_ref：保护的是从 last_node 到根的整条路径',['inc_lock_ref 沿 parent 向上走到根之前，每个经过节点都增加 lock_ref。只有 0→1 才将该段长度从 evictable_size_ 移入 protected_size_；额外请求共享路径会增加计数，但不重复计算受保护容量。','dec_lock_ref 做相反转换。若两个活动请求落在不同叶子，它们的公共祖先会同时受两条路径保护；释放一个请求不会解除另一个请求对公共前缀的保护。','cache_unfinished_req 可能将已完成后缀发布到树，再把保护锚点从公共节点移到新的末节点。图中会展示 last_node 与各段 lock_ref 随步骤一起变化。'],'只有叶子位置不够表达共享：保留后缀还必须保留它赖以续算的祖先，因此锁沿父链传播。','lock_ref 是路径引用；不能与 vLLM 每个 KVCacheBlock 的 ref_cnt 按字段一一互换。两者保护对象和计数更新方式不同。',['sg.radix#RadixCache.inc_lock_ref','sg.radix#RadixCache.dec_lock_ref','sg.radix#RadixCache.cache_unfinished_req']),
s('插入与结束：归一位置，留下可复用前缀',['cache_unfinished_req 插入已经算好的 token，对并发产生的重复前缀释放多余位置，再重新匹配树中的规范位置，回写请求表。仅仅收到 token IDs 并不表示这些位置已经算好，可以对外复用。','cache_finished_req 按 page 边界插入，释放重复部分与无法纳入缓存的未对齐尾部，最后解除活动路径锁。请求结束释放活动所有权，树内已完成前缀可以继续驻留。','Req.kv.cache_protected_len 表示树保护到哪里；Req.prefix_indices 还可能含未进入树的私有半页尾部，因此两者长度不保证相等。'],'用规范位置收敛并发重复计算，同时把“请求活跃”与“缓存驻留”分成独立生命周期。','已分配、已计算、已插入、已锁定是不同状态。统计命中和内存时必须说明正在度量哪一种。',['sg.radix#RadixCache.insert','sg.radix#RadixCache.cache_unfinished_req','sg.radix#RadixCache.cache_finished_req','sg.batch#Req']),
s('evict：从可驱逐叶子向上回收',['evict 从 evictable_leaves 建立策略堆，选出可驱逐叶子，将 node.value 对应位置交回 allocator，并删除树节点。父节点在变成无子节点且未锁定后，才可能成为下一轮候选。','经典树不能独立删掉一个仍支撑子路径的内部前缀。交互示例选择回收 A 的旧尾叶，公共四 token 与 B 的尾叶继续存在。图采用明确的教学淘汰选择；真实顺序由配置策略及访问状态决定。'],'叶子回收维持可恢复的连续路径，并让冷缓存让出实际物理容量。','evictable_size_ 是可回收缓存 token 位置的口径，不等于设备当前空闲空间；GPU、host 与在途搬运又有各自引用。',['sg.radix#RadixCache.evict','sg.radix#RadixCache._delete_leaf','sg.hicache']),
s('Prefix cache 的键与 K3 / V4 的恢复边界',['普通 token 前缀之外，RadixKey.extra_key 与 cache_salt 参与进程内树命名空间；不同命名空间不能因文本相同就共享。当前源码也明确指出，外部 L3/remote token-only 键不自动继承这份树内隔离约定。','page_size=2 时，公共前缀若只有三个 token，普通 page 对齐匹配仅保留两个；某些 EAGLE 路径还使用 bigram key。Radix 能表达分叉，不代表任意配置都允许逐 token 复用。','Kimi K3 必须同时恢复 MLA 历史和 KDA 的 conv/recurrent state，需继续读 Mamba/Unified cache。DeepSeek V4 需要 SWA、压缩历史与 partial compressor state 的共同有效边界。上图是经典 RadixCache 的位置与锁示例，并未把这些状态池简化成同一张 KV 表。'],'缓存键保证计算上下文一致，恢复边界保证所需状态齐全；两项同时满足才能继续正确计算。','实际选用的 cache 类取决于模型、配置与功能组合；不能从这张经典树直接推断 K3/V4 每种部署的池结构和命中长度。',['sg.radix#RadixKey.child_key_at','sg.radix#RadixKey.match_at','sg.cachebuilder','sg.mamba','sg.unified','sg.v4pool','sg.v4state'])]},
{id:'cache-vllm',group:'核心机制',title:'KV cache：vLLM 的块哈希链',subtitle:'逻辑指纹 → 分组哈希索引 → 物理块表 → 空闲双向链表',intro:'vLLM 把“这是什么前缀”与“它在哪个物理块”分开。Request.block_hashes 描述因果内容，BlockPool 用哈希索引找到 KVCacheBlock；请求持有块列表，空闲队列管理可回收块。沿这四层读，才能理解命中与释放。',tags:['vLLM','BlockHash','KVCacheBlock','BlockPool'],lab:'cache-vllm',related:['cache','hybrid','kda','sparse'],sections:[
s('哈希链：当前 token 块必须带上所有前文',['hash_block_tokens 计算 H(parent_block_hash, tuple(curr_block_token_ids), extra_keys)。第一个块使用 NONE_HASH 种子，之后每个块依赖前一个哈希。相同后缀接在不同前文后，会得到不同的下游指纹。','generate_block_hash_extra_keys 纳入 LoRA、多模态标识、prompt embeddings 的哈希以及 cache_salt；salt 在首块加入后，通过 parent hash 影响后续链。仅比较 token IDs 不足以表示所有输入条件。','Request.block_hashes 是按 hash_block_size 增量生成的逻辑指纹序列。输入已知时可以先生成哈希；只有 KV 已完成并登记进 BlockPool 后才有可复用条目。'],'因果 attention 的 K/V 来自含前文的隐藏状态，不能把重复局部文本当成相同计算。父哈希压缩了整段前文的身份。','图中 H1 等是方便阅读的身份标签，不是真实摘要。哈希单位、各组物理 block_size、调度对齐粒度在混合配置里可能不同。',['vl.kvutils#hash_block_tokens','vl.kvutils#generate_block_hash_extra_keys','vl.kvutils#get_request_block_hasher','vl.request#Request']),
s('两层映射：哈希键不是物理块号',['BlockPool.cached_block_hash_to_block 是 BlockHashToBlockMap。其键为 BlockHashWithGroupId，将内容哈希与 kv_cache_group_id 组合；同一前缀在不同缓存组中指向不同状态存储。','映射值可以是一个 KVCacheBlock，也可以是 block_id→KVCacheBlock 的字典。并发请求可能已经各自算出等价块，实现允许同一键保留多个物理副本，避免为强行去重改写既有块表。','KVCacheBlock 存 block_id、ref_cnt、_block_hash、_block_hash_num_tokens、prev_free_block、next_free_block、is_null。它是 CPU 元数据；模型实际 KV 张量按 block_id 定位。block_id=0 的 null block 具有特殊规则，不纳入下面普通块示例。'],'内容索引用于跨请求发现共享，物理 ID 用于稳定寻址。容忍少量重复可换取追加式块表与更简单的调度。','一对一“哈希→唯一块”的画法只适用于简单示例。当前实现还需要反向别名索引 cached_block_hashes_by_block 清理一个块的多个前缀键。',['vl.block#BlockHashToBlockMap','vl.block#BlockPool','vl.kvutils#KVCacheBlock','vl.kvutils#make_block_hash_with_group_id']),
s('Prefix hit：连续可用，不是独立命中块的集合',['FullAttentionManager.find_longest_cache_hit 从头依次查块；所需组的任一块缺失，就结束普通完整块阶段。较晚哈希即使还留在表中，也不能跳过中间缺失的 full-attention 历史继续复用。','KVCacheManager.get_computed_blocks 将最大命中长度限制为 request.num_tokens−1，需要重算尾 token 获得最后 logits。普通 block_size=2 时，六 token 的完全相同 prompt 最多先命中四 token，最后两 token 所在块仍需计算。','读前缀缓存还可能因 skip_reading_prefix_cache 或任务条件关闭。混合缓存由 coordinator 协调各组边界，返回的不只是“哈希相等的块数”。'],'命中结果必须是一段可以直接续算的状态；避免用缺失历史或缺失 logits 的结果推进生成。','哈希是否相等、索引是否驻留、组状态是否完整、调度允许复用多长，是四个独立条件。实验可以分别改变前文、盐和中间块驻留。',['vl.single#FullAttentionManager.find_longest_cache_hit','vl.block#BlockPool.get_cached_block','vl.kv#KVCacheManager.get_computed_blocks','vl.coordinator']),
s('touch 与 allocate：请求拿到哪些块',['SingleTypeKVCacheManager.req_to_blocks 为每个请求保存有序 KVCacheBlock 列表。示例 B 复用物理块 7、2，再分配块 12，逻辑块顺序是 [7,2,12]，物理 ID 无需连续。','命中时 touch 增加这些块的 ref_cnt；如果原计数为零，先把它从空闲队列摘除。新块由 get_new_blocks 从队首取得，移除旧缓存键后将 ref_cnt 增加到 1。','普通完整块在计算后由 cache_full_blocks 登记哈希。刚分配的块尚未完成时没有可复用哈希；它在请求块表中存在，不代表其他请求可以命中它。'],'按块的活动引用保护实际物理内存；命中只建立共享引用，不需要复制公共 KV。','共享块不能随意修改。当前 is_block_writable 要求非 null、ref_cnt=1 且没有已登记 hash；部分命中后的写入路径还需遵循对应 manager 的规则。',['vl.single#SingleTypeKVCacheManager','vl.kv#KVCacheManager.allocate_slots','vl.block#BlockPool.touch','vl.block#BlockPool.get_new_blocks','vl.block#BlockPool.cache_full_blocks','vl.block#BlockPool.is_block_writable']),
s('空闲双向链表：零引用仍可以命中',['FreeKVCacheBlockQueue 将 KVCacheBlock 自身的 prev_free_block / next_free_block 串起来，用 fake_free_list_head / tail 哨兵处理边界。哈希链是逻辑依赖；这两根指针是物理块回收队列的链接，没有 parent hash 的指针语义。','free_blocks 减少 ref_cnt。变成零的已缓存块被追加到队尾，保留哈希等待复用；未缓存块优先放到队首。SingleTypeKVCacheManager.free 逆序交回请求块，令同批释放的尾块更早被回收。','命中队列中间的块时，可凭块对象在 O(1) 时间摘除，不必扫描队列；嵌入指针也避免每次操作新建链表节点。'],'把“没有活动用户”作为回收候选条件，同时延长已完成前缀的复用寿命。','空闲块不等于空内容块；ref_cnt=0 也不等于哈希已删除。只看 free queue 长度无法推导缓存命中率。',['vl.kvutils#FreeKVCacheBlockQueue','vl.kvutils#KVCacheBlock','vl.block#BlockPool.free_blocks','vl.single#SingleTypeKVCacheManager.free']),
s('真正重用时才移除旧索引',['get_new_blocks 从队首取块后，_maybe_evict_cached_block 清理旧哈希与别名，再把这块交给新请求。图中 A 的尾块 9 在被 C 分配时失去旧映射；其余公共前缀块继续可命中。','不同于树的祖先依赖，物理块回收无需修改一棵 token 树。后缀的哈希可以独立留在映射里，但 full attention 检索仍要求前面的状态连续可用。','显式 evict_blocks 还可以撤销活动块的缓存索引而不回收其物理内存。这里同样要区分“从 prefix cache 失效”和“把 GPU 块释放给别的请求”。'],'让稳定物理块表与可变内容索引各自维护不变量，避免前缀热度变化牵动请求地址。','正确清理所有别名是必要条件，否则旧键可能命中新内容。淘汰策略的收益取决于请求分布，不能把缓存保留数等同于节省时间。',['vl.block#BlockPool.get_new_blocks','vl.block#BlockPool._maybe_evict_cached_block','vl.block#BlockPool.evict_blocks']),
s('当前实现的细粒度命中：物理半块也可有索引',['本页固定快照已包含 cache_partial_block：它为已有物理块的内部前缀边界登记一个入口，不因登记动作分配或复制新 KVCacheBlock。没有主哈希时设为主键，否则放入 cached_block_hashes_by_block 管理的别名。','当 alignment_tokens 与 hash_block_size 支持更细粒度且小于组 block_size 时，FullAttentionManager 在完整块阶段后，从长到短探测第一个未完整命中块的内部边界。举例：物理块 4 token、hash 单位 2 token，可在已登记且有效的 2-token 内部边界命中。','因此图中“每块两个 token，只命中整块”仅表示三种粒度恰好相同的普通 full-attention 示例。块内缓存键、有效 token 数、后续可写性与跨组边界必须一起检查。'],'分开内容指纹粒度与物理分配粒度，可以在混合模型要求的恢复位置保留前缀，减少粗粒度对齐导致的重算。','支持细粒度索引不等于所有配置任意 token 都能复用；也不能把登记时无需复制推广为后续续写永远无需状态处理。',['vl.block#BlockPool.cache_partial_block','vl.kvutils#resolve_block_hashes','vl.kvutils#BlockHashListWithBlockSize','vl.single#FullAttentionManager.find_longest_cache_hit']),
s('放回 Kimi K3 与 DeepSeek V4 看',['Kimi K3 的 MLA 历史和 KDA 状态不能共享同一个“token block”解释。MambaSpec 与对应 manager 表示有限状态，coordinator 需要找出这些状态和 attention 历史的共同恢复边界。','DeepSeek V4 的 SWA、压缩历史及 compressor/indexer 相关状态也有不同保留与访问约束。某一组的哈希命中并不自动证明完整模型可以从那里继续。','与 SGLang 对照时，应分别比较内容键、状态规格、请求映射、活动引用和回收策略；不要把 TreeNode 改名成 KVCacheBlock 就声称实现等价。'],'跨组 prefix cache 的正确单位是“完整模型可以恢复的前缀状态集合”。数据结构差异正是在维护不同粒度的状态。','本页聚焦 V1 cache 主干，具体模型仍要继续阅读 specs、coordinator 和模型生成的状态布局；运行配置决定采用哪些细粒度路径。',['vl.specs#MambaSpec','vl.single','vl.coordinator','vl.k3','vl.v4attn','vl.compressor'])]}
];
