import {cacheChapters} from './cacheContent.ts';
export type Section = {title:string; body:string[]; principle:string; tradeoff:string; refs:string[]};
export type Chapter = {id:string; group:string; title:string; subtitle:string; intro:string; tags:string[]; sections:Section[]; compare?:[string,string,string][]; lab?:string; related:string[]};
const s=(title:string,body:string[],principle:string,tradeoff:string,refs:string[]):Section=>({title,body,principle,tradeoff,refs});
export const chapters:Chapter[]=[
{id:'overview',group:'建立全局',title:'推理引擎的全景地图',subtitle:'从一次请求，看清两套系统如何组织计算',intro:'推理框架的核心，是把不规则、持续到达的请求，转成 GPU 能高效执行且状态一致的批次。SGLang 与 vLLM 都在同时管理三件事：每个请求算到哪里、历史状态放在哪里、下一轮怎样计算。',tags:['架构','进程','数据流'],lab:'map',related:['lifecycle','scheduler','cache'],sections:[
s('先沿着三条主线读代码',['控制流：HTTP 接收 → 输入处理 → 等待/运行队列 → 调度 → 执行 → 输出。调度器决定本轮服务哪些请求，模型类本身不决定请求优先级。','数据流：token IDs / 多模态 embeddings → batch metadata → hidden states → logits → token IDs。批次在 CPU 与 GPU 之间转换表示，Python 请求对象通常不会原样传进 kernel。','状态流：请求逻辑位置 → 物理 KV 页/递归状态槽 → 命中、分配、写入、引用、回收。缓存不仅是张量；状态的生命周期和可复用边界同样重要。'],'分离控制、执行与状态管理，让模型算子和服务策略可以独立演化。','拆分会引入 IPC、元数据构造和同步成本；小批次时，这些开销可能比算子更突出。',['sg.scheduler#Scheduler','sg.forward#ForwardBatch','vl.core#EngineCore','vl.output#SchedulerOutput']),
s('两套系统的组织重心',['SGLang 的阅读主轴是 TokenizerManager、Scheduler、TpModelWorker、ModelRunner。ScheduleBatch 与 ForwardBatch 串起调度层和执行层，Radix/Unified Cache 负责跨请求复用。当前 scheduler 还拆出了接收、输出、指标等组件。','vLLM 的阅读主轴是 AsyncLLM、EngineCore、Scheduler、Executor/Worker、GPUModelRunner。V1 scheduler 使用已计算 token 与目标 token 的差额组织调度，KVCacheSpec 与 Coordinator 对齐多种缓存。','这不是互斥能力表：两者都有 continuous batching、prefix caching、MoE、并行和投机解码。比较时应对齐模型、硬件、精度、流量分布与 SLO。'],'按责任边界比较，比按产品标签比较更能解释实现差异。','同一仓库常保留多个 runner/backend。这里默认分析 Python GPU 主路径，分支以配置和平台选择为准。',['sg.batch#ScheduleBatch','sg.worker','vl.async#AsyncLLM','vl.runner','vl.runner2']),
s('覆盖范围与证据口径',['本图谱覆盖服务入口、调度、分页与混合缓存、执行与编译、attention、MoE、并行通信、PD 分离、投机、量化、多模态/输出协议、运维、测试和扩展，并深入两种指定模型。','源码定位固定在本地 2026-09-06 核对的提交；配置来自当天读取的官方 Hugging Face 文件。网页中的行号由 Python AST 提取，源码全文按原样快照保存。','解释框标注“设计原理/代价”时，是从实现推导的工程分析；模拟器是教学模型，不是 GPU 性能测试。SGLang diffusion/前端 DSL、训练系统及每个硬件 kernel 的逐指令分析不属于本文主线。'],'先确定版本与适用范围，结论才可复核。','官方 main 会继续演化；固定提交链接用于复现，部署前仍需确认新版本。',['sg.registry','vl.registry'])],compare:[['服务控制','TokenizerManager + Scheduler','AsyncLLM + EngineCore + Scheduler'],['调度表示','ScheduleBatch / ForwardMode','Request token 差额 / SchedulerOutput'],['缓存组织','Radix 树、混合组件、内存池','BlockPool、KVCacheSpec、Coordinator'],['模型执行','TpModelWorker → ModelRunner','Executor / Worker → GPUModelRunner']]},
{id:'lifecycle',group:'建立全局',title:'一次请求的完整旅程',subtitle:'入口、队列、GPU、流式输出与资源释放',intro:'HTTP 返回流只是外壳。真正的生命周期跨越输入处理进程、调度状态机、执行设备和输出处理。理解每一步的所有者，是排查卡住、取消失效与显存泄漏的起点。',tags:['HTTP','IPC','tokenizer','stream'],lab:'trace',related:['scheduler','serving','operations'],sections:[
s('输入与进程边界',['SGLang 的 HTTP 层交给 TokenizerManager 编码、构建请求，再经通信通道交给 scheduler。detokenizer 将批量 token 转为文本，tokenizer manager 管理面向调用方的流式结果。','vLLM 的 API server 连接 AsyncLLM；输入经验证与处理后发送到 engine core，输出处理器把 EngineCoreOutputs 还原为调用方可消费的结果。EngineCore 与前端分离，可避免 HTTP/字符串处理阻塞 GPU 调度。'],'CPU 密集的编码、媒体处理和字符串拼接不应占住关键调度路径。','更多进程不自动更快：序列化、拷贝和队列等待需要观测。短 prompt、高 QPS 时前端可能先饱和。',['sg.http','sg.tokenizer#TokenizerManager','sg.detokenizer#DetokenizerManager','vl.http','vl.async#AsyncLLM']),
s('首 token 与后续 token 不是同一条成本曲线',['Prefill 处理未命中的 prompt 部分，attention 需要支持多 query，通常具有更大的矩阵计算；decode 通常每请求新增一个 query，重复读取权重和历史状态。这里是工作负载趋势，不能把所有 prefill 都断言为 compute-bound。','首 token 延迟包含排队、编码、前缀恢复、prefill 与采样。后续 token 间隔还受调度频率、批大小、通信、cache 读取和输出缓冲影响。','请求全部命中缓存也不保证零次 forward：首个生成 token 的 logits、最后位置状态或模型特定尾块约束可能要求保留/重算尾部。'],'把 TTFT 拆开，才能分清“算得慢”和“等得久”。','仅测模型 forward 会漏掉用户真实感知的队列和网络延迟。',['vl.core#EngineCore.step','vl.kv#KVCacheManager.get_computed_blocks','sg.scheduler#Scheduler.get_next_batch_to_run']),
s('完成、取消与异常同样属于执行链路',['正常结束可能由 EOS、stop 字符串、最大输出长度或结构化生成状态触发。释放请求的活动引用后，物理缓存仍可能作为可复用前缀保留；“请求结束”不等于“缓存立即清空”。','取消请求需要通知 engine，让未发出的调度停止，并安全处理在途 GPU 工作。异步调度下，提前复用仍被 kernel 读取的内存会产生竞态，必须遵守执行完成边界。'],'资源释放要绑定真实的在途使用状态，而不是仅绑定 HTTP 连接。','跨进程取消、连接器传输失败和运行时异常要分别验证；不能只测 happy path。',['sg.tokenizer','sg.scheduler','vl.async','vl.scheduler#Scheduler.update_from_output','vl.block#BlockPool'])]},
{id:'scheduler',group:'核心机制',title:'调度：把不规则请求变成批次',subtitle:'Continuous batching、chunked prefill 与 CPU/GPU overlap',intro:'调度并非简单凑够 batch size。它受 token 预算、请求槽、KV 空间、encoder 预算以及投机验证状态共同约束；每轮决策都会改变延迟、公平性与吞吐。',tags:['调度','chunk','抢占','overlap'],lab:'scheduler',related:['cache','execution','speculation'],sections:[
s('从“请求数量”转为“本轮工作量”',['vLLM Scheduler.schedule 的注释明确：调度算法不显式区分 prefill/decode phase，而让 num_computed_tokens 追上 num_tokens_with_spec，并考虑异步输出 placeholders。本轮工作量再被 token budget、最大长度等裁剪。','SGLang 显式组织运行 decode batch 与新 prefill/extend，get_next_batch_to_run 返回 batch plan；ScheduleBatch 准备各模式的数据。不同表示都可以支持连续加入和移出请求。'],'以 token 工作量控制资源比固定请求数更合理：1 个超长 prompt 的开销可远超几十个 decode token。','统一抽象不消除模式差异；底层 metadata 和 kernels 仍要区分多 query prefill、decode、验证。',['vl.scheduler#Scheduler.schedule','sg.scheduler#Scheduler.get_next_batch_to_run','sg.batch#ScheduleBatch']),
s('Chunked prefill 为什么能改善尾延迟',['把长 prompt 分成可调度块，避免一个大 prefill 长时间占用 GPU，给已有 decode 请求留下执行机会。前缀命中可减少需要 prefill 的 token 数，但只有在状态完整可恢复时才成立。','块太小会增加调度次数、kernel 启动、重复读取和对齐浪费；块太大又可能扩大 decode 的等待。最佳阈值取决于硬件、上下文长度和并发。','内存不够时，引擎可能暂停或抢占请求，回收空间后重算。不要将重算理解成免费的队列移动：它消耗先前已经付过的算力。'],'对长任务分时，控制它对正在交互用户的干扰。','吞吐、TTFT、ITL 和公平性存在目标冲突；没有适用于所有流量的单一 batch 设置。',['sg.policy','vl.scheduler#Scheduler.schedule','sg.scheduler#Scheduler.get_next_batch_to_run']),
s('Overlap 是依赖管理问题',['SGLang event_loop_overlap 把 CPU 处理与 GPU 计算交叠，使用结果队列在合适时机处理上一批输出；某些批次需要关闭 overlap。','vLLM 有 AsyncScheduler 和在途输出占位机制；提前发出下一轮时，必须精确记录哪些 token/状态尚未确认，以及哪些块只能延迟释放。','CPU 不等待每个小结果，可以填掉 GPU 的调度空洞；但它不能让同一请求绕过自回归依赖。投机或预先 staging 也必须最终处理接受/拒绝结果。'],'把能提前做的准备提前，把真实依赖留在同步边界。','竞争条件通常出现在取消、投机拒绝、抢占和 slot 重用的组合上。',['sg.scheduler#Scheduler.event_loop_overlap','vl.asyncscheduler','vl.scheduler'])]},
...cacheChapters,
{id:'hybrid',group:'核心机制',title:'混合状态：超越一张 KV 表',subtitle:'Full attention、KDA、SWA 与压缩状态的共同边界',intro:'Kimi K3 与 DeepSeek V4 都迫使缓存管理从“每层同样的 K/V”走向多种状态协作。一个请求能复用多长前缀，取决于所有必要状态能否在同一个位置恢复。',tags:['KDA state','SWA','Coordinator','checkpoint'],related:['kimi','kda','deepseek','cache'],sections:[
s('K3：token 历史与递归摘要并存',['MLA 保存随序列长度增加的 latent cache；KDA 保存短卷积历史与递归矩阵。后者在一个边界是前缀的摘要，却无法随机读取任意旧 token 的 K/V。','如果 MLA 命中到 4096，而 KDA 只有 2048 的有效状态，不能直接从 4096 继续。需要寻找共同可恢复点，或者从更早 checkpoint 重算缺失部分。','vLLM 用 MambaSpec 表示这类有限状态缓存；名称 Mamba 不表示 K3 使用了 Mamba 模型。SGLang 有 Mamba/Unified cache 组件来管理递归状态。'],'复用的单位应是可继续计算的状态集合，而不是单层命中长度。','存更多 checkpoint 会提高复用粒度，也会占用额外显存；“固定状态大小”不意味着多前缀缓存没有增长。',['vl.specs#MambaSpec','vl.coordinator','vl.single','sg.mamba','sg.unified']),
s('V4：窗口、压缩页与未完成分组',['SWA 保存近期细粒度信息，C4/C128 保存不同压缩率的历史。压缩器还需要保存未完成窗口的 partial state，不能仅传输已产出的 compressed KV。','SGLang 的 DeepSeek V4 专用 pool 对 SWA、C4、C128 与压缩中间状态分别组织容量和索引；vLLM 将 compressor、indexer、SWA 等对象接到缓存规格与 metadata 体系。','chunk 边界、压缩分组边界与物理页边界是不同概念。尤其在 chunked prefill 或 speculative verify 中，不能用一个 seq_len 推断所有状态都完整可用。'],'缓存的语义分层决定 allocator 和 metadata 的设计，而不是反过来。','在线压缩、MTP 与不同后端存在额外约束；能力要看具体实现分支。',['sg.v4pool','sg.v4state','vl.compressor#CompressorStateCache','vl.swa','vl.specs']),
s('统一抽象需要保留差异',['SGLang UnifiedRadixCache 把 FULL、MAMBA、SWA 等组件接在统一树结构上，侧重共同前缀、各组件资源和层级存储操作的协调。','vLLM KVCacheCoordinator 通过不同 group/manager 组织多种 KVCacheSpec，处理命中粒度与共同分配。调度块粒度需要兼容各组，不等于每个 kernel 的原生 block size。'],'统一的是生命周期与协议，异构状态保留自己的布局、有效区间和恢复方式。','若把所有状态强行当成等长 token 页，会在截断、回滚、前缀共享和传输时出错。',['sg.unified','sg.tree','vl.coordinator#KVCacheCoordinator','vl.single'])]},
{id:'execution',group:'核心机制',title:'执行层：从 batch 到 GPU kernels',subtitle:'Worker、metadata、图捕获与编译边界',intro:'模型 forward 只是执行链路的一部分。高效推理还要稳定输入缓冲、减少 Python 调度、选择合适的 attention backend，并让量化、通信和图捕获共享一致的约束。',tags:['ModelRunner','CUDA Graph','compile','metadata'],related:['attention','quantization','parallel'],sections:[
s('Runner 是控制平面与模型之间的适配层',['SGLang TpModelWorker 调用 ModelRunner，ForwardBatch 携带位置、请求池索引、KV 写入位置和模式等信息。attention backend 据此准备当前批次 metadata。','vLLM worker 负责设备和执行环境，GPUModelRunner 把 SchedulerOutput 转为 GPU 输入/缓存表、选择图模式并执行模型。当前仓库同时有 gpu_model_runner.py 与新 gpu/model_runner.py 路径，选择取决于配置。'],'集中处理批次物化，让模型层专注张量计算与结构。','优化模型类却忽略输入整理，可能在小 batch 下看不到端到端收益。',['sg.worker','sg.runner','sg.forward#ForwardBatch','vl.runner','vl.runner2']),
s('CUDA Graph 解决启动开销，不消除动态性',['Graph replay 复用捕获的 GPU 工作图，减少 CPU kernel launch 开销。常见做法是按 batch bucket 捕获，用固定地址的缓冲区装入变化的数据。','shape、地址和控制流需符合捕获条件；实际请求数可能 padding 到较大的 bucket。attention metadata、投机状态索引和通信缓冲也要配合 staging。','vLLM 的 CUDAGraphDispatcher 与 compilation backend 决定分派/分段策略；SGLang 的 runner 目录分别组织 graph base、decode 和 prefill 捕获路径。'],'把可重复执行形态静态化，把变化转化为缓冲中的数据。','捕获占用内存、启动耗时和 padding 都有成本；eager fallback 是能力的一部分，而非必然的缺陷。',['sg.graph','sg.graphbase','vl.graph','vl.compile']),
s('算子融合的正确粒度',['投影、norm、quant、RoPE、cache write 常可融合，减少中间张量读写；MoE 的路由与通信也可和相邻步骤组织流水。','但大而全的 fusion 会增加寄存器压力、限制 shape/dtype、扩大编译成本。K3 的小 token GEMM、V4 的 fused norm/RoPE/cache store 都是具体形状和硬件条件下的选择。'],'先定位带宽、启动或通信瓶颈，再选择融合边界。','某个 fast path 存在不等于当前运行会命中；必须检查 capability、dtype、shape、并行度和开关。',['sg.k3','vl.kda#is_fused_kda_decode_supported','vl.v4attn#_resolve_dsv4_kv_cache_dtype','vl.platform'])]},
{id:'attention',group:'核心机制',title:'Attention：算法、布局与后端',subtitle:'不要把 FlashAttention、PagedAttention 和 MLA 混为一谈',intro:'三种优化处在不同维度：FlashAttention 优化计算的 IO，分页优化缓存物理管理，MLA 改变模型保存的信息表示。KDA 与 V4 的压缩稀疏 attention 又进一步改变历史访问语义。',tags:['FlashAttention','MLA','backend','metadata'],related:['kda','sparse','cache'],sections:[
s('分清优化层次',['FlashAttention 用分块和 online softmax 避免物化完整 attention score 矩阵；不因采用它就自动具有跨请求前缀缓存。','PagedAttention 让 attention kernel 从页表读取不连续 KV，核心是虚拟序列到物理存储的映射。','MLA 以低维 latent 表示历史，在 decode 可通过权重吸收减少读取展开的多头 K/V。KDA 则递归更新状态；V4 通过窗口加压缩历史，进一步改变每个 query 要读取的候选集合。'],'计算组织、存储组织、模型表示应分别讨论，再分析组合效果。','压缩或递归注意力属于模型结构，不能作为任意 dense 模型的无损 runtime 开关。',['sg.attention','vl.attention','vl.mla','vl.v4attn']),
s('Backend 接口真正承载的契约',['后端要声明支持的 head size、dtype、block size、attention 类型和图捕获能力，并提供 metadata builder 与计算实现。选择层负责将模型/平台条件映射到后端。','metadata 可能包含 query 起始偏移、seq_lens、block table、slot mapping、稀疏索引、压缩长度与有效 mask。错误的 metadata 能让数值正确的 kernel 读错 token。'],'把“算什么”和“数据在哪里”显式传入，允许复用 kernel 并独立测试映射逻辑。','后端回退必须保持语义，包括 causal 边界、sink、soft cap、LSE 合并与量化 scale。',['vl.attention#AttentionBackend','vl.attention#AttentionMetadataBuilder','sg.attention','sg.attnregistry','vl.attnregistry']),
s('在线 softmax 与分区合并',['若历史分成多个页、设备或稀疏 source，不能对各自 softmax 输出直接求平均。每个分区需要携带归一化信息，例如 log-sum-exp。','对分区输出 O₁、O₂ 和 LSE l₁、l₂，合并权重是 exp(l₁−L)、exp(l₂−L)，其中 L=logaddexp(l₁,l₂)。这样才能等价于在合并候选集合上归一化。','这个原理同时出现在 prefix/suffix attention 合并、split-K、context parallel 和 V4 的多 source sparse attention 中。'],'分块可以改变执行顺序，但必须保留全局归一化的数学关系。','attention sink 也影响分母；空分区、全 mask 与重复索引都需要单独处理。',['vl.mla','vl.flashmla','sg.v4attn'])]},
{id:'moe',group:'核心机制',title:'MoE：路由、专家与通信',subtitle:'少激活参数，不代表没有内存与网络瓶颈',intro:'MoE 将每个 token 路由到少量专家，节省激活计算，但全部专家权重仍需存储或分布。推理成本来自路由、重排、dispatch、专家 GEMM、combine 和共享路径的整体。',tags:['MoE','EP','Top-k','负载均衡'],related:['parallel','kimi','deepseek'],sections:[
s('一个 MoE 层的实际步骤',['router 计算专家分数 → top-k 选专家与权重 → token 按专家重排/发送 → 每个专家执行 gate/up、激活、down → 按 routing weight 合并 → 与 shared experts 组合。','FusedMoE 封装了 kernel 与通信接口，不表示所有步骤都在一个 kernel 内完成。vLLM modular kernel 将准备/完成与专家计算分开，SGLang 也有独立 topk 和 MoE runner/backend。'],'按专家聚合 token，把不规则路由转为批量矩阵运算。','小 batch 时每个专家拿到的 token 很少，GEMM 效率差；EP 跨设备时还需付出通信启动延迟。',['sg.topk','sg.moe','vl.moe','vl.modularmoe']),
s('并行度与负载倾斜',['Tensor Parallel 切专家内部矩阵；Expert Parallel 分布不同专家。两个轴不是同一件事，可以按硬件与流量组合。','某些专家被频繁选择时，最繁忙 rank 决定完成时间。专家重映射/冗余专家有助于负载均衡，但会增加权重存储和管理成本。','低延迟 dispatch 偏向小消息快速完成，高吞吐 dispatch 偏向批量与带宽利用。DeepEP、MegaMoE 等路径的收益依赖网络、设备与批次规模。'],'优化最慢的关键路径，而不是只看所有专家的平均工作量。','更多 EP rank 不一定更快；通信可能超过节省的计算。',['sg.parallel','vl.parallel','vl.v4#DeepseekV4MoE','sg.k3#KimiK3MoE']),
s('两个模型的 MoE 不可直接等同',['K3 把 routed path 从 hidden 7168 降到 latent 3584，带 norm、896 专家、top-16；共享专家路径保持原空间。降维可以减少 routed 计算/传输，但引入投影和归一化。','V4 Flash/Pro 的专家数和宽度不同，采用 sqrtsoftplus scoring、top-6，且前几层有 hash routing 配置。不要把所有层都描述成同一种 learned router。','K3 的 SiTU 激活与 V4 的带 clamp SwiGLU 也不同。量化/融合 kernel 必须匹配激活、scale 和路由归一化语义。'],'框架通用接口之下仍需保持模型特定数值契约。','模型参数量、激活参数与端到端延迟没有固定比例关系。',['sg.k3#KimiK3MoE','vl.latentmoe','vl.v4#DeepseekV4MoE','config.kimi-k3','config.deepseek-v4-flash'])]},
{id:'parallel',group:'系统扩展',title:'分布式：每条并行轴解决什么',subtitle:'TP、PP、DP、EP、CP 与通信重叠',intro:'并行配置本质上决定权重、token、历史状态和专家分别放在哪些设备上。先画清张量布局，再讨论 collective，才能解释扩卡后的收益或退化。',tags:['TP','PP','DP','EP','DCP'],lab:'parallel',related:['moe','disaggregation','kimi'],sections:[
s('权重、请求、专家与序列的不同切法',['TP 切矩阵/attention heads，层间常需 all-reduce 或 reduce-scatter；PP 切层，用 P2P 传 hidden states，批量不足时有 pipeline bubble。','DP 分请求或 batch，复制相应执行资源；DP attention + EP 可以让 attention 按请求分摊，同时让 MoE 使用更大的专家池。','CP 按上下文历史/序列切分。DCP 主要服务 decode 历史缓存与 attention 计算；PCP 处理 prefill 序列，二者在模型与后端支持上应分别检查。'],'为最大的瓶颈选择切分维度：权重容量、KV 容量、矩阵效率或专家容量。','并行轴可能共享或嵌套 process groups，不能把所有 size 不加区分地相乘当 GPU 数。',['sg.parallel','vl.parallel','vl.mla']),
s('K3 的具体通信重构',['当前 SGLang K3DecoderLayer 的 SP-MoE 分支将 attention o_proj 的 TP reduction 改为 reduce-scatter，使 MoE 前端与专家 dispatch 在 token shard 上执行，再 all-gather 回来。','这样可避免同一 attention TP 组重复 dispatch 完整 token batch，并减少共享专家侧的冗余；但只适用于满足条件的 MoE 层/后端，dense 层不能简单套用。','vLLM K3 MLA 中 DCP manager 明确存在；PCP 仍有 assert 限制。这与旧报告“DCP/PCP 均不支持”的结论不同。'],'用布局转换消除重复工作，而不是仅替换一个更快的 collective。','并行优化改变张量所有权与同步次序，需同时验证 padding、量化、graph capture 和分支回退。',['sg.k3#KimiK3DecoderLayer','sg.k3sp','vl.mla#MultiHeadLatentAttention']),
s('重叠通信的前提',['把共享专家计算与 routed 专家通信放在不同 stream 上，或采用两个 micro-batch 交错，可覆盖部分等待。','重叠要求独立工作、可并行的设备资源与正确 event 依赖；若两个任务都已占满带宽，重叠可能只是在争用。V4 中可看到 TBO 操作拆分，vLLM 则有 DBO/ubatching 相关路径。'],'以关键路径时间判断收益，不能把并行任务耗时简单相减。','需要实际 profiler trace；网页的时间线只说明依赖关系，不给未经实测的加速数字。',['sg.v4#DeepseekV4Model','vl.v4','vl.parallel'])]},
{id:'disaggregation',group:'系统扩展',title:'PD 分离与分层缓存',subtitle:'把计算分开之后，状态必须完整迁移',intro:'Prefill 与 decode 的最佳资源配置不同，PD 分离让它们独立扩缩。但网络和状态恢复从辅助工作变成首 token 的关键路径。',tags:['PD','HiCache','NIXL','KV transfer'],related:['hybrid','parallel','operations'],sections:[
s('Prefill 到 decode 的交接协议',['Prefill 节点生成 prompt 状态；decode 节点准备可写入的物理槽，完成传输与可用性确认后继续生成。bootstrap、元数据交换、数据拷贝和完成通知缺一不可。','SGLang disaggregation 下有 prefill/decode 队列与传输协调；vLLM KVConnector 区分 scheduler 侧与 worker 侧职责，NIXL 等 connector 提供具体传输实现。'],'独立扩展计算密集与持续解码资源，减少相互干扰。','只有节省的排队/计算干扰大于新增传输和协议成本时才获益；短 prompt 不一定适合。',['sg.prefill','sg.decode','vl.connector','vl.nixl']),
s('混合模型交接比普通 KV 更复杂',['K3 需要同步 MLA cache 与 KDA conv/recurrent state 的边界；V4 还需 SWA、压缩历史、indexer 和 partial compressor state。只传 visible KV 不保证能继续正确生成。','发送与接收两侧的 TP/CP 布局、精度和块格式可能不同，需要 connector 明确支持转换，不能仅因为两边都能运行模型就默认兼容。'],'迁移的是可恢复的执行状态，不是随意的一段显存。','投机在途状态、传输失败重试、请求取消和缓存生命周期会形成组合边界。',['sg.v4state','sg.v4pool','vl.connector','vl.compressor']),
s('GPU、主存、存储三层之间的选择',['HiCache/分层缓存用主存或外部存储延长前缀的可复用寿命。GPU 是低延迟热点层，主存容量大但受总线限制，外部存储容量更大但延迟更高。','异步预取需要足够提前量；写回需要锁定在途源/目标，避免页被重用。系统还要决定命中后是恢复还是重新计算更划算。'],'用容量换取可复用性，再以预取和调度隐藏部分传输。','命中率不足以判断效果：命中的大小、恢复带宽和等待时间同样重要。',['sg.hicache','sg.unified','vl.connector'])]},
{id:'speculation',group:'系统扩展',title:'投机解码：一次验证多个候选',subtitle:'Draft、verify、accept 与混合状态恢复',intro:'投机解码把便宜的候选生成和昂贵的目标模型验证结合起来。它的价值取决于接受长度、验证成本以及状态维护开销，而不是单看 draft 模型多快。',tags:['EAGLE','MTP','rejection','DSpark'],lab:'speculation',related:['kda','sparse','scheduler'],sections:[
s('候选不等于最终输出',['draft 提出若干 token，target 对候选路径做验证，再依据算法接受一段前缀、产生修正或 bonus token。贪心一致性与随机采样的分布校正是不同的验证情形。','vLLM 有 proposer 与 RejectionSampler 等实现；SGLang 的 EAGLE worker 负责 draft/verify 协作。MTP 是模型额外预测模块，可以作为候选来源，但不意味着每次都接受所有预测。'],'用一次较高并行度的 target forward 覆盖多个潜在 decode 步骤。','接受率低、batch 已很大或通信很重时，草拟和验证的额外工作可能抵消收益。',['sg.spec','vl.spec','vl.reject','sg.v4mtp','vl.v4mtp']),
s('为什么 KDA 的回滚更难',['普通 KV 可以通过有效长度与槽映射丢弃未接受尾部；KDA 的递归更新把历史折叠进状态，无法仅缩短长度就撤销更新。','实现需保存可选择的状态/checkpoint，或使用专门的恢复记录。当前 vLLM K3 的状态 shape/dtype 逻辑包含 use_kda_recoverssm 分支，说明恢复策略不能只沿用旧 PR 的“每候选完整状态槽”描述。','V4 也要撤销未接受候选写入的压缩 partial state，尤其当候选跨越 C4/C128 边界时。'],'接受 token 数必须同步决定所有状态组件的有效边界。','投机验证、前缀缓存和异步调度组合起来，最容易暴露尾部状态污染。',['vl.kdametadata','vl.k3','vl.mambashape','sg.v4state','sg.v4pool']),
s('模型能力与发布权重分开看',['官方 K3 本次读取的 text_config.num_nextn_predict_layers 为 0，仓库中仍可有 MTP/DSpark 支持。应明确额外 draft checkpoint 与算法配置，不能从类文件存在推断默认启用。','本次读取的 V4 Flash/Pro 配置均含 1 个 nextn 预测层。压缩比数组比主干层数多一项，末尾属于预测层配置，不能把它算成主干层。'],'模型结构、checkpoint 内容、运行开关共同决定可执行路径。','理论 speedup 必须结合目标验证时间与期望接受长度；页面提供可调的简化成本模型，不代表实测。',['config.kimi-k3','config.deepseek-v4-flash','config.deepseek-v4-pro','vl.k3mtp','vl.v4mtp'])]},
{id:'kimi',group:'模型深潜',title:'Kimi K3：三条信息混合轴',subtitle:'93 层 · Hybrid KDA–MLA · Block AttnRes · LatentMoE',intro:'K3 同时改变序列、深度和通道方向的信息流：69 层 KDA 与 24 层 Gated NoPE-MLA 处理序列；Block AttnRes 聚合深度；Stable LatentMoE 处理稀疏通道计算。',tags:['Kimi K3','69 KDA','24 MLA','AttnRes'],lab:'layers-k3',related:['kda','kimi-depth','hybrid'],sections:[
s('从真实配置还原每一层',['官方配置使用 1-based 层号：第 4、8、…、92 和第 93 层为 MLA，其余 69 层为 KDA。第一层使用 dense FFN，后续 92 层为 MoE。交互图可逐层选择并跳到两套 decoder 实现。','hidden size 7168，96 attention/KDA heads，KDA head dim 128；routed experts 896，top-16，shared experts 数为 2，routed hidden 3584，expert intermediate 3072。这里采用官方配置数值，不采用 cookbook 中“+1 shared”的旧注释。','最大位置 1,048,576 是 checkpoint 的配置能力，不等于任意设备在该长度下都能服务。text_config 的 KimiLinearForCausalLM 名称来自复用配置脚手架，并不代表它与早期 Kimi Linear 完全相同。'],'看配置的层映射与具体分派，不能仅由类名判断模型。','K3 checkpoint 存在量化/裁剪衍生版本；这里的层图来自 moonshotai/Kimi-K3。',['config.kimi-k3','sg.k3#KimiK3DecoderLayer','sg.kdaconfig','vl.k3']),
s('NoPE-MLA 保留了 64 维分支',['K3 MLA 不做 RoPE，但配置仍保留 qk_rope_head_dim=64 这一历史名字；这段维度仍参与投影与 cache。NoPE 不等于把这段张量删除。','每 token 的逻辑 latent cache 是 512+64=576 个元素。24 层 MLA 的 BF16 payload 为每 token 27,648 bytes，未计 padding、量化 scale、metadata 或并行复制。','decode 使用吸收后的 query/输出投影，在 latent 历史上做 attention，避免对所有历史 token 展开多头 K/V；prefill 则有不同的投影与计算路径。'],'减少随序列长度增长的历史读取，同时用层间 KDA 提供序列信息。','NoPE 是训练后的模型结构，不能将普通 MLA 推理时关闭 RoPE 当成等价优化。',['vl.mla#MultiHeadLatentAttention','sg.k3#KimiK3MLAAttention','config.kimi-k3']),
s('从模型结构推导服务瓶颈',['KDA 让许多层的历史变成固定状态，但 24 层 MLA 仍随上下文增长；模型整体缓存绝不是 O(1)。','896 专家带来巨大权重容量，top-16 影响激活计算与 dispatch；latent path 降维缓解部分成本。AttnRes 和视觉前处理又带来独立的临时状态与计算。','因此 K3 部署要联合看权重、MLA cache、KDA 状态槽、前缀 checkpoint、图捕获缓冲和临时激活，不能只套用一个 KV bytes/token 公式。'],'逐类核算长期状态与瞬时峰值，再决定并行和容量。','本页面内存实验只算明确列出的 payload，不能作为设备数量承诺。',['vl.k3','vl.latentmoe','vl.mambashape','sg.k3'])]},
{id:'kda',group:'模型深潜',title:'KDA：递归状态如何进入推理框架',subtitle:'短卷积、Delta rule、chunk prefill 与状态 checkpoint',intro:'KDA 的 decode 读取并更新一个矩阵状态，不遍历全部历史 token。但 prefill 需要高效并行处理长序列，前缀复用与投机也必须能恢复到正确的状态边界。',tags:['KDA','Delta rule','FlashKDA','state'],lab:'memory',related:['kimi','hybrid','speculation'],sections:[
s('状态更新的概念形式',['单头状态 S 可按维度约定写成 dₖ×dᵥ 的矩阵；本步先按通道 decay 衰减旧状态，再以 k 和目标 v 的预测误差作 rank-one 校正，最后由 q 读取输出。示意：S̄=Diag(α)S，S′=S̄+βk(v−kᵀS̄)ᵀ，o=qᵀS′。转置约定以具体 kernel 为准。','K3 使用短因果卷积准备 Q/K/V、lower-bounded log decay（配置 lower bound −5）、full-rank output gate，以及 per-head norm。bounded decay 约束也参与 FlashKDA fast path 选择。'],'用可更新摘要压缩历史，让单步状态访问量不随序列长度线性增加。','状态是有损结构化摘要，不能像 full attention 那样随机访问任意历史 KV；这必须由训练设计补偿。',['vl.kda#KimiK3DeltaAttention','sg.k3#KimiK3DeltaAttention','sg.kda','config.kimi-k3']),
s('Prefill 和 decode 是两种并行方式',['decode 沿时间递归，每请求只推进少量新 token；可融合 short-conv update、recurrence、norm 和 gate 来减少启动与中间读写。','prefill 需要利用 chunk 内并行计算，chunk 之间传递状态。vLLM resolve_kda_prefill_backend 会选择 FlashKDA 或 Triton 路径，FlashKDA 对 CUDA capability、BF16、head dim 和 bounded gate 有要求。','当前 fused decode 的支持检查还要求 conv width 4、head dim 128、特定 head 数、无 speculative token、对应自定义 op 和设备能力。它不是所有 KDA 输入都能使用的默认数学实现。'],'同一递归关系可采用不同执行分解，以适应多 token 和单 token 的硬件效率。','融合路径与 fallback 的浮点顺序可能不同，应比对误差容忍范围与端到端输出质量。',['vl.kda#resolve_kda_prefill_backend','vl.kda#is_fused_kda_decode_supported','sg.kda']),
s('固定状态也可能很大',['无 speculative/额外恢复记录时，每层 conv payload 是 (3×96×128/TP)×3 个元素；状态矩阵为 (96/TP)×128×128。conv 的实际内存方向由 layout 决定，不影响此处元素数。','按 BF16 conv 与 FP32 recurrent 计算，69 层每请求一份状态在 TP=1 时约 428.6 MiB，TP=8 时每 rank 约 53.6 MiB。MLA 单 rank cache 不能默认也除 TP：其 latent 存储可能复制，DCP 才进一步分摊历史。','prefix checkpoint、多候选状态、RecoverSSM 记录和 allocator 对齐均是额外项。实验中明确分开 KDA 的 head 分片与 MLA 的历史分片。'],'“随长度不增长”和“绝对数值很小”是两回事。','容量应按活跃请求数与持有的 checkpoint 数一起估算。',['vl.mambashape#MambaStateShapeCalculator.kda_state_shape','vl.k3#KimiLinearForCausalLM.get_mamba_state_shape_from_config','vl.mla'])]},
{id:'kimi-depth',group:'模型深潜',title:'K3 的 AttnRes 与 Stable LatentMoE',subtitle:'深度聚合、降维路由和融合的边界',intro:'普通 residual 直接相加；K3 的 Block AttnRes 选择性聚合之前的 block 表征。MoE 又把 routed 分支投到低维空间。这两种改变都直接影响推理时的临时状态与 kernel 设计。',tags:['AttnRes','LatentMoE','SiTU','fusion'],related:['kimi','moe','parallel'],sections:[
s('沿深度做 attention，不是沿 token 做 attention',['每个 token 保留当前 block prefix sum 与已完成 block 表征。子层用各自的 norm/打分参数，计算历史来源的权重，得到送入 attention 或 MLP 的输入。','配置 block size 为 12；到 block 边界时写入完成的表征，维护当前累加状态。这里的数据沿网络深度存在，不应误标成跨请求的序列 KV cache。','sglang attn_residual 与 vLLM attn_res kernels 可融合 prefix 更新、block 写入、打分、softmax 聚合及输出 norm，减少中间张量流量。'],'以分块降低对所有层中间表征逐层保留和扫描的成本，同时允许深度信息选择。','多来源聚合仍比简单 residual 更复杂；边界层、首层和尾部 partial block 需要分别处理。',['sg.attnres','sg.k3#KimiK3DecoderLayer._forward_attn_residual','vl.attnres','vl.k3']),
s('Stable LatentMoE 的两条路径',['routed path 对 hidden 7168 做投影到 3584、归一化、专家计算，再投回原空间；shared experts 在全宽空间提供共享计算。路由与 latent 输入是不同职责，不要默认 router 只看降维后的表示。','latent_moe_use_norm 和 SiTU-GLU 的 β 参数来自模型配置。它们改变数值函数，融合/量化后仍需保留，不能简单替换成普通 SwiGLU。','降维减少 routed experts 的矩阵宽度及某些 dispatch payload，却新增前后投影。小 token batch 时，这些窄矩阵投影和通信启动占比会升高。'],'用一个共享低维瓶颈减少大量专家上的重复宽矩阵开销。','参数与 FLOPs 的下降不自动转化为相同比例延迟改善；还需看 grouped GEMM 利用率和网络。',['sg.k3#KimiK3MoE','vl.latentmoe','vl.k3','config.kimi-k3']),
s('为什么模型代码里有这么多 fast path',['当前实现有权重合并、输出缓冲复用、共享/routed overlap、小 batch GEMM 与通信融合等条件分支。它们在不同 token bucket、dtype 与 TP/EP 布局下选择不同边界。','不要逐个记开关；先确认输入布局、计算结果归约发生在哪里，以及共享输出和 routed 输出何时可相加。再沿 eligibility 检查找到当前硬件能走的路径。'],'保持同一数值契约，针对不同硬件工作点选择执行计划。','权重视图、持久缓冲和异步 stream 使初始化/加载与 forward 紧密相关，不能只阅读 forward 一个方法。',['sg.k3#KimiK3MoE._eligible_for_fused_front','vl.latentmoe','sg.k3#KimiK3LinearForCausalLM.post_load_weights'])]},
{id:'deepseek',group:'模型深潜',title:'DeepSeek V4：压缩历史与多流残差',subtitle:'Flash / Pro 的层配置、稀疏访问、mHC 与 MoE',intro:'V4 的主线是用近期窗口保留局部细节，用压缩历史承接长程信息，再以层特定策略选择历史。mHC 改变深度残差通路，MoE 承担稀疏 FFN 计算。',tags:['DeepSeek V4','C4','C128','mHC'],lab:'layers-v4',related:['sparse','moe','quantization'],sections:[
s('Flash 和 Pro 不能共用一张参数表',['官方 Flash 配置：43 层、hidden 4096、64 query heads、256 routed experts、top-6、index_topk 512。Pro：61 层、hidden 7168、128 query heads、384 routed experts、top-6、index_topk 1024。两者 sliding_window 均为 128，head_dim 512，hc_mult 4。','Flash 主干前两层 compress_ratio=0，之后 C4/C128 交替并以 C4 结束；Pro 前两层为 C128，之后也按配置交替。不是每一层都同时运行 C4 与 C128。','两份 compress_ratios 数组都比 num_hidden_layers 多 1 项，末尾为 MTP 层的 0。网页按主干层数切片，预测层单独标出。'],'逐层配置决定模块构建与池容量；模型家族名不能替代 checkpoint 配置。','这里选原始 Flash/Pro，不将 0731、0813 或 Vision-Exp 混成同一版本。',['config.deepseek-v4-flash','config.deepseek-v4-pro','sg.v4#DeepseekV4DecoderLayer','vl.v4#DeepseekV4Model']),
s('Attention 与 MoE 的实现分层',['SGLang MQALayer 负责投影、RoPE、压缩/indexer 协作和后端调用；DeepseekV4AttnBackend 与专用 memory pool 承载 metadata 和存储。','vLLM 将通用 DeepseekV4Attention、compressor、sparse MLA 与 NVIDIA/AMD/XPU 后端分开，模型构造按平台选具体类。FlashMLA/FlashInfer 是可选执行实现，不是模型结构本身。','前 num_hash_layers=3 层有 token-ID 到专家的 hash routing 表；其余 learned routing 用 sqrtsoftplus 分数与 top-k 机制。输入 token IDs 因此仍可能在 MoE 阶段有直接用途。'],'把模型共享语义与硬件实现拆开，允许专用 kernel 演进。','默认 config 类的 max_position/head 字段可能只是构造兜底；正式值要读 checkpoint。',['sg.v4#MQALayer','vl.v4attn#DeepseekV4Attention','vl.v4#_select_dsv4_attn_cls','vl.v4#DeepseekV4MoE']),
s('mHC：四条残差流如何保持稳定',['hc_mult=4 使每 token hidden 拓展为多条残差流；hc_pre 产生送入子层的聚合表示和混合参数，hc_post 将子层输出写回多流，并混合旧 residual。','Sinkhorn 迭代用于归一化 residual mixing，使混合具有受约束的结构。它与 K3 的“按深度选择过去 block”不同：mHC 的重点是多残差流之间的受约束映射。','vLLM 的 mhc kernel 与 SGLang MhcOps 包含 pre、post、fused post-pre、head 等操作，融合减少层与层之间的中间读写。'],'约束深度通路的混合，抑制无约束残差组合造成的尺度问题。','额外 residual streams、归一化和混合带来带宽与临时内存成本；不是无代价的替代残差。',['vl.mhc','vl.v4#DeepseekV4DecoderLayer','sg.v4#MhcOps','sg.v4#DeepseekV4DecoderLayer'])]},
{id:'sparse',group:'模型深潜',title:'V4 稀疏注意力：一次 query 读什么',subtitle:'SWA + C4 检索，或 SWA + C128 历史',intro:'V4 不是“给普通 MLA 加一个 top-k”这么简单。压缩产生候选历史，indexer 选择部分候选，SWA 保留近邻细节，metadata 将这一切变为 kernel 可访问的物理位置。',tags:['稀疏','indexer','compressor','SWA'],lab:'sparse',related:['deepseek','attention','hybrid'],sections:[
s('C4 与 C128 分工',['C4 层把历史压缩为较细粒度的候选，再用 indexer 选 top-k；候选数小于 top-k 时可直接选择全部，当前 vLLM 有这一短上下文优化。','C128 压缩更强，读取更粗的历史摘要，不应把 C4 的 top-k 检索流程原样套给它。ratio=0 的层没有这条压缩分支。各层同时保留近期 SWA。','压缩是带学习权重/门控的聚合并配合 norm、RoPE、cache store；它不是简单每 4 或 128 token 取算术平均。C4 的实际重叠窗口和写出节奏也要分开看。'],'用多尺度表示平衡近期精细信息与远程历史容量。','压缩引入信息损失和额外计算；模型训练与层间组合决定能力，runtime 不能任意修改比例。',['vl.compressor#DeepseekCompressor','vl.v4attn#DeepseekV4Indexer','sg.v4pool','config.deepseek-v4-flash']),
s('Metadata 才是因果性的第一道防线',['当前 query 只能看到已完成且在其因果范围内的压缩组。prefill 中每个 query 的位置不同，不能统一用整条 prompt 的最终长度。','逻辑稀疏索引还要映射到物理 KV 页，处理 SWA ring、压缩写入边界、padding 和无效位置。只检查 attention 输出 shape 无法发现这类错误。','SWA 和压缩 source 需要统一归一化，attention sink 也可能进入分母；错误地单独归一化后平均会改变模型函数。'],'先构造正确的可见集合，再让 kernel 高效地计算这个集合。','边界测试应覆盖 3→4、127→128、chunk 断点、缓存命中后的 extend 和投机拒绝。',['sg.v4attn','vl.swa','vl.indexer','vl.flashmla','vl.sparse']),
s('压缩存储量与每步访问量不同',['C4 即使每步只读 top-k，仍可能需要保留更多压缩候选和 indexer 状态。因此不能用“top-k×head_dim”直接估计全部 KV 显存。','C128 历史随上下文仍增长，只是增长斜率较低。固定 SWA 并不意味着整个 V4 模型 cache 为常数。','实验里分别显示逻辑已完成组数、读取的候选数和未完成分组；候选分数用确定性教学数据生成，不模拟真实 learned indexer。'],'区分容量成本与访问成本，才能解释长上下文下的显存和延迟。','实际池大小含分层、CP、ring、量化尺度和对齐，不能从简化可见集合倒推出精确设备显存。',['sg.v4pool','sg.v4state','vl.v4attn','vl.compressor'])]},
{id:'quantization',group:'服务与工程',title:'量化与硬件：格式不是执行能力',subtitle:'权重、激活、KV 与状态精度必须分别核对',intro:'“FP4 模型”并不意味着全部张量都以 4 bit 计算。checkpoint 存储格式、kernel 输入格式、累加精度和输出/缓存格式是不同契约。',tags:['FP4','FP8','BF16','A100','backend'],related:['execution','moe','operations'],sections:[
s('从 checkpoint 到 kernel 的完整路径',['K3 官方文本配置将部分 Linear 权重按 MXFP4 group 32 打包，并明确排除 attention、shared experts、视觉等模式。V4 配置同时出现 expert_dtype=fp4 与 FP8 quantization_config，说明不同模块使用不同精度。','加载器要映射权重名、读取 scales、切分 TP/EP、合并投影，并可能 repack 或做加载后转换。forward 里的矩阵调用只是最终环节。','KV 精度另由 cache 设置和后端决定。V4 fp8_ds_mla 是有特定 scale/packed layout 的格式，不是把任意 FP8 row 直接改一个 dtype 名称。'],'让存储、分片、布局和 kernel 解码方式完全一致，量化才能正确。','repack 会有启动时间与峰值内存；低位宽权重仍可能需要 BF16/FP32 中间量。',['config.kimi-k3','config.deepseek-v4-flash','vl.loader','vl.v4quant','vl.v4attn#_resolve_dsv4_kv_cache_dtype']),
s('A100、Hopper、Blackwell 的选择边界',['硬件对低精度 tensor core、指令集、共享内存、网络和原生 kernel 的支持不同。能装下某个 checkpoint，不等于能直接调用它的最优 FP4 kernel。','A100 上的 V4 需要核对现有 backend、权重转换/回退与 BF16/FP8 路径。本地 deepseek-v4-a100-sglang 是定制适配项目，其 BF16 sparse kernel 与格式转换结论不能直接归为上游默认支持。','后端选择应从模型 overrides、platform、quant config 与 capability 检查逐层确认，再用实际启动日志验证。'],'把“算法可实现”“框架已有路径”“本机能运行”分成三个证据层次。','不要只通过架构名宣传硬件支持；shape、精度、并行、MTP 组合可能另有限制。',['sg.v4override','sg.k3override','vl.platform','vl.v4#_select_dsv4_attn_cls','sg.v4recipe']),
s('量化验收看什么',['先做单算子参考比较，再看模型 logits/输出一致性与任务质量，最后在真实长度和并发分布下测端到端。','路由分数、norm、激活 clamp、softmax 与递归状态的数值敏感性不同，不能假设所有模块适合相同精度。KDA 的 recurrent FP32 状态就是一个需要独立核算的例子。'],'性能优化须保留模型可接受的质量与稳定性。','token/s 提升若来自更短输出、不同采样参数或精度退化，不构成公平对比。',['vl.mambashape','sg.k3','vl.v4','vl.sampler'])]},
{id:'serving',group:'服务与工程',title:'服务语义：文本、视觉、采样与工具',subtitle:'模型能 forward，只完成了服务的一部分',intro:'Chat 模板、视觉编码、采样与结构化输出共同决定用户看到的行为。它们必须和模型 checkpoint、tokenizer、stop 规则以及流式协议保持一致。',tags:['多模态','sampling','grammar','tool','LoRA'],related:['lifecycle','kimi','testing'],sections:[
s('K3 多模态路径不是把图片当文本',['K3 vision config 包含 patch size 14、27 层视觉塔、空间/时间位置处理与 patch merger，再映射到文本 hidden 7168。图像/video 的 patch 数会影响 encoder 工作量和 prompt token 长度。','SGLang multimodal processor 负责媒体预处理与占位关系；K3 model 提取并合并图像特征。vLLM renderer/model 也有媒体输入、特征投影与 encoder graph 路径。','多模态缓存必须识别真实媒体内容或其稳定 ID，不能只因为 placeholder token 相同就共享缓存。'],'先编码非文本信息，再把媒体 embedding 与文本位置正确对齐。','视觉预处理/encoder 是独立瓶颈；部分模型版本是 text-only，不能把 V4 Vision-Exp 支持泛化到原始 Flash/Pro。',['config.kimi-k3','sg.k3process','sg.k3#KimiK3ForConditionalGeneration','vl.k3render','vl.k3']),
s('采样与受约束生成',['logits 经过 penalties、temperature、top-k/top-p、grammar mask 等处理后抽样。其顺序与语义要跟随 sampler 实现，不能将所有后处理混成纯前端功能。','结构化生成通过状态机/grammar 限制下一步合法 token；工具调用 parser 与 reasoning parser 负责识别模型实际协议，并组织流式增量。合法 JSON 不自动意味着正确的工具语义。','K3 和 V4 的特殊 token、reasoning/tool 格式不同；vLLM 与 SGLang 都有各自的模型特定处理。'],'把生成约束和结果解析分开：一个影响模型分布，一个解释模型输出。','测试需覆盖分块流式 token、转义、截断、空工具参数和结束标记跨 chunk。',['sg.sampler','vl.sampler','sg.grammar','vl.grammar','sg.k3parser','vl.k3parser','vl.v4parser']),
s('多租户、LoRA 与接口承诺',['LoRA 管理器组织 adapter 加载与调度侧约束；cache key 也必须区分影响隐藏状态的 adapter。某个模型声明 SupportsLoRA 不等于所有量化/并行组合都已验证。','OpenAI-compatible 描述协议兼容，不保证模型模板、reasoning 字段与工具语义完全一致。embedding、pooling、rerank 等是不同输出任务，不能套用生成模型的全部流程。'],'接口抽象降低接入成本，模型特定语义仍需显式适配。','服务验收要覆盖模板与输出协议，不能仅以 HTTP 200 或首 token 返回作为正确性标准。',['vl.lora','vl.registry','sg.registry','vl.http'])]},
{id:'operations',group:'服务与工程',title:'性能诊断与运维',subtitle:'用现象定位层次，用完整口径比较引擎',intro:'没有固定的“哪个框架更快”。模型、精度、并行布局、上下文分布、prefix 命中和目标延迟不同，可能改变结论。先找到瓶颈，再改配置。',tags:['TTFT','ITL','SLO','profiling','OOM'],lab:'diagnosis',related:['scheduler','parallel','testing'],sections:[
s('建立可比的基准',['固定两份代码提交、checkpoint revision、tokenizer、dtype/quant、GPU 拓扑、驱动/通信库与启动参数。工作负载需同时给输入/输出长度、并发或到达率、采样设置与 prefix 热度。','报告 TTFT、ITL/TPOT 分布、请求吞吐、输出 token/s、总 token/s、错误率与超时，并说明是否含 warmup、tokenization 和排队。','将冷缓存/热缓存、低并发/饱和流量分开。压力超过容量时，队列持续增长，平均 token/s 仍可能很好看，但用户尾延迟已失控。'],'比较同一服务目标下的有效吞吐，而不是选择最有利的一个数字。','网页没有运行 GPU 推理，因此不提供两个引擎的实测排名。',['sg.scheduler','vl.scheduler','sg.k3recipe','sg.v4recipe']),
s('按症状逐层排查',['TTFT 高：先看队列/编码/encoder，再看 prefix 命中、恢复与 prefill。ITL 高：看是否混入大 prefill、batch bucket、attention 带宽与 MoE 通信。','OOM：拆开权重、KV、KDA state、graph pool、临时激活和加载峰值。扩卡变慢：检查 TP/EP 消息大小、跨节点路径、最忙 rank 与同步等待。','偶发乱码或结果漂移：核对模板、量化 scale、slot mapping、prefix key、投机接受边界；不应先把它们都归因于模型随机性。'],'让性能与正确性假设能落到具体模块和可观测信号。','一次 profiler trace 只覆盖一个工作点，应复现原始流量和触发条件。',['sg.runner','vl.runner','sg.v4pool','vl.kdametadata']),
s('生产系统还有控制平面',['请求路由、DP 负载分配、cache-aware routing、限流、健康检查、优雅退出和失败重试在模型之外决定可用性。SGLang 的 Rust gateway/router 是独立服务组件，不是每次本地 generate 必经路径。','失败恢复不能只重连网络；PD 或 offload 在途状态必须确认完成/失效。权重更新也要确保与活跃请求、cache 的一致性。'],'把可用性与过载控制作为推理系统的一部分。','路由策略会改变 cache 热度和排队，因此也会改变引擎级 benchmark 观察到的结果。',['sg.http','sg.tokenizer','vl.http','vl.connector'])]},
{id:'testing',group:'服务与工程',title:'扩展与验证：从模型到可用服务',subtitle:'新增模型、后端或优化时应该守住什么',intro:'框架扩展最困难的部分，是让新实现同时符合模型数学、缓存状态、调度边界和服务协议。只实现 forward 通常还不足以完成接入。',tags:['registry','单元测试','E2E','porting'],related:['sources','execution','serving'],sections:[
s('新增模型的最小闭环',['注册 config/model architecture → 构造层与并行参数 → 对齐 checkpoint 命名与加载 → 声明 attention/状态规格 → logits/采样 → 多模态与 parser（若需要）。','K3 需要 Mamba state shape/dtype/copy 接口与混合 cache；V4 需要 compressor/indexer/SWA 规格及模型特定参数。模型 registry 只是入口，不是完整适配层。'],'每个模块应明确输入输出与状态所有者，避免隐式共享假设。','复用已有父类时，要核对保留的命名/默认行为是否仍符合新模型，例如 K3 的 NoPE 分支。',['sg.registry','vl.registry','vl.k3','vl.v4attn','vl.loader']),
s('验证那些最容易坏的边界',['数值层：对照高精度/参考实现，覆盖实际 dtype/shape。映射层：验证页表、slot mapping、padding、空稀疏集合与 causal 边界。','状态层：测试 prefix hit→extend、chunked prefill→decode、请求抢占→恢复、投机接受/拒绝跨 C4/C128、KDA checkpoint 恢复。','服务层：多并发、取消、EOS/stop、工具调用流式分片、多模态占位与 PD 失败。源码阅读器也收录了模型与缓存的真实回归测试，可按文件名搜索。'],'测试针对可观察行为与状态不变量，而不只重复实现的分支。','通过单 kernel 测试不保证端到端质量；反过来，E2E 输出偶然一致也不能证明边界映射正确。',['test.vllm.test_deepseek_v4_swa_visible','test.vllm.test_indexer_deepseek_v4_slot_mapping','test.sglang.test_dsv4_compress_write_pad','test.sglang.test_unified_radix_cache_kl_dsv4']),
s('建议的阅读路线',['第一遍：入口 → scheduler → batch/metadata → runner → cache manager，理解所有权与时间顺序。第二遍：K3 decoder → KDA/MLA → AttnRes/MoE；V4 decoder → compressor/indexer → sparse backend → pool。','第三遍选择一个问题，如“投机拒绝 3 个 token 后状态如何恢复”，从调度输出追到 kernel metadata，再回到回归测试。带着不变量读代码，比逐文件通读更有效。'],'用可检验的问题把层与层连起来，形成可以迁移到新模型的理解。','学习图中的连接是精选的职责/调用关系，不冒充静态分析生成的完整 call graph。',['sg.scheduler','vl.scheduler','sg.k3','vl.v4','vl.kdametadata'])]},
{id:'sources',group:'服务与工程',title:'源码与资料：可复核的分析基线',subtitle:'固定提交、原始配置、框架选择与范围说明',intro:'每个“查看源码”都在站内打开真实文件，并定位到核验过的函数/类行号。可切换符号、搜索文件内容、复制仓库内位置，也可打开固定提交的 GitHub 页面。',tags:['证据','版本','框架选择','源码'],lab:'sources',related:['overview','testing'],sections:[
s('资料优先级',['一级：本地两份仓库的固定提交与真实测试。二级：2026-09-06 读取并保存的官方 Kimi K3 / V4 Flash / V4 Pro 配置。三级：本地技术报告与既有分析用作线索，遇到冲突以原始配置和当前实现为准。','例如 K3 shared experts 的 cookbook 注释与正式配置不一致，本图谱选择配置的 2；旧报告的 K3 DCP 限制已按当前 vLLM 分支更正。','模型配置的远程 main 链接是可变的，因此本网页保留下载快照及 SHA-256；源码 GitHub 链接则固定 commit，二者不要混为同一种版本保证。'],'让事实、解释与模拟的来源透明，可让未来更新有明确复核点。','分析全面覆盖主干职责，但不宣称穷尽仓库每一个模型和硬件插件。',['config.kimi-k3','config.deepseek-v4-flash','config.deepseek-v4-pro','vl.mla']),
s('网页框架的检索与选择',['已读取 Vite 官方入门、React Flow 官方介绍、Docusaurus 官方文档。Docusaurus 适合以 MDX 为主的文档站，提供文档版本、搜索与导航生态；React Flow 专长是节点关系图的缩放、移动与交互。','本任务的核心是联动的架构图、实验控件与源码侧栏，因此选择 React + Vite + React Flow，搭配 Prism 语法着色和 Lucide 图标。页面可构建成静态网站，无需部署模型或连接远程推理服务。','所有核心资源与源码快照均随构建输出保存；运行时不依赖 CDN。源码以按文件加载减少首次打开的数据量。'],'让框架匹配主要交互，不为单页学习工具引入不必要的后端。','这是可继续维护的本地网站，不含在线协作、账户或 GPU 执行。',['sg.registry','vl.registry'])]}
];
export const groups=[...new Set(chapters.map(c=>c.group))];
export const modelDeepDives = [
  {id:'kimi', title:'Kimi K3', sections:[
    {id:'kimi', title:'架构总览'},
    {id:'kda', title:'KDA 与状态缓存'},
    {id:'kimi-depth', title:'AttnRes 与 LatentMoE'},
  ]},
  {id:'deepseek', title:'DeepSeek V4', sections:[
    {id:'deepseek', title:'架构总览'},
    {id:'sparse', title:'压缩与稀疏注意力'},
  ]},
];
export const chapterFamilies = [...modelDeepDives, {id:'cache',title:'KV cache',sections:[{id:'cache',title:'SGLang · Radix Tree'},{id:'cache-vllm',title:'vLLM · 块哈希链'}]}];
export const familyForChapter = (id:string) => chapterFamilies.find(model=>model.sections.some(section=>section.id===id));
export const navigationChapters = chapters.filter(chapter=>{
  const model=familyForChapter(chapter.id);
  return !model || model.id===chapter.id;
});
export const frameworkLinks=[{name:'Vite · Getting Started',url:'https://vite.dev/guide/'},{name:'React Flow · Interactive diagrams',url:'https://reactflow.dev/'},{name:'Docusaurus · Documentation',url:'https://docusaurus.io/docs'}];
