import {RadixLab, VllmCacheLab} from './CacheLabs';
import {useState} from 'react';
import {ArrowRight,ChevronLeft,ChevronRight,RotateCcw,GitBranch,Database,SlidersHorizontal} from 'lucide-react';
import {References} from './References';
import {type Engine,type OpenCode,sourceIndex,repoName} from './data';
import {scheduleDemo,k3Memory,sparseDemo,speculativeEstimate} from './simulations.mjs';
import kimi from './kimi-config.json';
import flash from './flash-config.json';
import pro from './pro-config.json';
type Props={kind:string;open:OpenCode;engine:Engine;go:(id:string)=>void;theme:'light'|'dark'};
const fmt=(n:number)=>n.toLocaleString('zh-CN',{maximumFractionDigits:1});
const MiB=1024**2;
function Head({label,title,note}:{label:string;title:string;note?:string}){return <div className="lab-heading"><div><span className="eyebrow">{label}</span><h3>{title}</h3></div>{note&&<span className="subtle-tag">{note}</span>}</div>}
function Range({label,value,onChange,min,max,step=1,unit=''}:{label:string;value:number;onChange:(v:number)=>void;min:number;max:number;step?:number;unit?:string}){return <label className="control"><span>{label}<output>{fmt(value)} {unit}</output></span><input type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(+e.target.value)}/></label>}
function Trace({open,engine}:Props){
 const [step,setStep]=useState(0),[model,setModel]=useState('k3');
 const stages=[['输入处理','messages / 图片 → tokens / embeddings','请求已创建，还没有可执行 GPU batch。','sg.tokenizer','vl.async'],['进入调度','waiting → running','检查 token 预算、请求槽和缓存容量；已有前缀可能减少 prefill 工作量。','sg.scheduler','vl.scheduler'],['恢复前缀','逻辑位置 → 共同有效边界',model==='k3'?'MLA 历史与 KDA 状态必须在共同边界可用。':'SWA、compressed KV 和 partial compressor state 必须一致。','sg.unified','vl.coordinator'],['准备执行','批次计划 → metadata / slot mapping','将可变请求转成张量索引，并选择 eager 或 CUDA Graph。','sg.forward','vl.runner'],['模型 forward',model==='k3'?'KDA / MLA → AttnRes → LatentMoE':'SWA + 压缩历史 → mHC → MoE','这里只是层次概览；残差聚合发生在子层前后，具体顺序见 decoder。',model==='k3'?'sg.k3':'sg.v4',model==='k3'?'vl.k3':'vl.v4'],['采样 / 验证','logits → accepted tokens','约束和采样决定真实输出；投机模式还要确定被接受的状态。','sg.sampler','vl.reject'],['回写与输出','更新边界 → 流式文本','已确认 token 影响下一轮调度，未接受的候选状态不能继续使用。','sg.detokenizer','vl.scheduler#Scheduler.update_from_output'],['结束或继续','decode loop / release','未完成请求回到调度；完成则释放活动引用，前缀可作为缓存保留。','sg.radix','vl.block']];
 const current=stages[step];
 return <div className="lab"><Head label="REQUEST WALKTHROUGH" title="逐步推进一次请求"/><div className="lab-controls"><label>模型 <select value={model} onChange={e=>setModel(e.target.value)}><option value="k3">Kimi K3</option><option value="v4">DeepSeek V4</option></select></label><div className="step-controls"><button className="icon-button" aria-label="上一步" disabled={!step} onClick={()=>setStep(step-1)}><ChevronLeft size={18}/></button><span>{step+1} / {stages.length}</span><button className="button primary" disabled={step===7} onClick={()=>setStep(step+1)}>下一步 <ChevronRight size={14}/></button><button className="icon-button" aria-label="重置流程" onClick={()=>setStep(0)}><RotateCcw size={16}/></button></div></div><div className="trace-steps">{stages.map((s,i)=><button key={s[0]} onClick={()=>setStep(i)} aria-pressed={step===i} className={i===step?'active':i<step?'done':''}><span>{String(i+1).padStart(2,'0')}</span>{s[0]}</button>)}</div><div className="trace-detail" aria-live="polite"><span className="eyebrow">STEP {step+1}</span><h4>{current[1]}</h4><p>{current[2]}</p><References refs={[current[3],current[4]]} open={open} engine={engine}/></div></div>
}
function SchedulerLab(){
 const [budget,setBudget]=useState(8),[chunk,setChunk]=useState(8),[first,setFirst]=useState(true),[step,setStep]=useState(0);
 const rounds=scheduleDemo({budget,chunk,decodeFirst:first}),shown=Math.min(step,rounds.length-1);
 const reset=(fn:()=>void)=>{fn();setStep(0)};
 return <div className="lab"><Head label="SCHEDULING LAB" title="改变 token 预算，观察谁先得到服务" note="教学调度器 · 非引擎回放"/><div className="control-grid"><Range label="每轮 token 预算" min={4} max={32} step={4} value={budget} onChange={v=>reset(()=>setBudget(v))}/><Range label="单请求 prefill chunk" min={4} max={32} step={4} value={chunk} onChange={v=>reset(()=>setChunk(v))}/></div><div className="lab-controls"><label className="check"><input type="checkbox" checked={first} onChange={e=>reset(()=>setFirst(e.target.checked))}/>优先已有 decode</label><button className="button" disabled={shown===rounds.length-1} onClick={()=>setStep(shown+1)}>推进一轮 <ArrowRight size={14}/></button><button className="icon-button" aria-label="重置调度" onClick={()=>setStep(0)}><RotateCcw size={16}/></button></div><p className="small muted">A：已有 decode，剩 4 token；B：24 token prompt + 4 token 输出；C：第 3 轮到达，8 token prompt + 3 token 输出。简化模型独立计算首个 decode，不计算耗时、抢占、缓存和首 token 与 prefill 的融合。</p><div className="schedule-table"><div className="schedule-row schedule-head"><span>轮次</span><span>请求 A</span><span>请求 B</span><span>请求 C</span><span>预算使用</span></div>{rounds.slice(0,shown+1).map(r=><div className="schedule-row" key={r.round}><span>#{r.round}</span>{['A','B','C'].map(id=>{const slot=r.slots.find(x=>x.id===id);return <span key={id}>{slot?<span className={`work-slot ${slot.phase}`}>{slot.phase==='decode'?'D':'P'} · {slot.tokens}</span>:<span className="muted">—</span>}</span>})}<span>{r.used} / {budget}</span></div>)}</div><div className="lab-foot" aria-live="polite">第 {shown+1} 轮 / 共 {rounds.length} 轮 · P = prefill，D = decode。轮数不等于延迟：不同 token 组成的轮次耗时不同。</div></div>
}
function MemoryLab(){
 const [context,setContext]=useState(32768),[requests,setRequests]=useState(1),[tp,setTp]=useState(8),[dcp,setDcp]=useState(1),[kvBytes,setKvBytes]=useState(2);
 const d=k3Memory({context,requests,tp,dcp,kvBytes});
 const segments=[{name:'MLA 历史',n:d.mla,cl:'mla'},{name:'KDA recurrent',n:d.recurrent,cl:'kda'},{name:'KDA short-conv',n:d.conv,cl:'conv'}];
 return <div className="lab"><Head label="MEMORY LAB" title="K3：固定状态与增长中的历史" note="payload 估算 · 不是容量保证"/><div className="control-grid"><Range label="每请求上下文长度" min={1024} max={131072} step={1024} value={context} onChange={setContext} unit="tokens"/><Range label="活跃请求数" min={1} max={32} value={requests} onChange={setRequests}/></div><div className="lab-controls"><label>KDA head 分片 TP <select value={tp} onChange={e=>{setTp(+e.target.value);setDcp(1)}}>{[1,2,4,8,16].map(n=><option key={n}>{n}</option>)}</select></label><label>MLA 历史分片 DCP <select value={dcp} onChange={e=>setDcp(+e.target.value)}>{[1,2,4,8,16].filter(n=>n<=tp).map(n=><option key={n}>{n}</option>)}</select></label><label>MLA 元素字节 <select value={kvBytes} onChange={e=>setKvBytes(+e.target.value)}><option value={2}>BF16 · 2 bytes</option><option value={1}>FP8 payload · 1 byte</option></select></label></div><div className="memory-total" aria-live="polite"><span>单 rank · 所选请求的简化状态总量</span><strong>{fmt(d.total/MiB)} <small>MiB</small></strong></div><div className="memory-bar" role="img" aria-label={segments.map(s=>`${s.name} ${fmt(s.n/MiB)} MiB`).join('，')}>{segments.map(s=><div key={s.name} className={s.cl} style={{width:`${s.n/d.total*100}%`}}/>)}</div><div className="memory-legend">{segments.map(s=><div key={s.name}><i className={s.cl}/><span>{s.name}</span><strong>{fmt(s.n/MiB)} MiB</strong></div>)}</div><details><summary>公式与边界</summary><p>MLA = 24 × 576 × 元素字节 × 长度 × 请求数 ÷ DCP；KDA recurrent = 69 × 96 ÷ TP × 128² × 4 × 请求数；conv = 69 × (3 × 96 × 128 ÷ TP) × 3 × 2 × 请求数。</p><p>假设每请求一份 KDA 状态、所有层在同一 PP stage、MLA 在 TP 中复制且理想按 DCP 切历史。未计权重、FP8 scale/布局、prefix checkpoint、投机/RecoverSSM、graph、临时激活、padding 和 allocator。DCP 的现实兼容性还取决于后端。</p></details></div>
}
function LayersLab({kind,open,engine}:Props){
 const k3=kind==='layers-k3';const [variant,setVariant]=useState('flash'),[selected,setSelected]=useState(0);
 const config=variant==='flash'?flash:pro,n=k3?93:config.num_hidden_layers;
 const ix=Math.min(selected,n-1);
 const typeOf=(i:number)=>k3?(kimi.text_config.linear_attn_config.full_attn_layers.includes(i+1)?'MLA':'KDA'):config.compress_ratios[i]===0?'SWA':`C${config.compress_ratios[i]}`;
 const type=typeOf(ix);
 return <div className="lab"><Head label="MODEL LAYER EXPLORER" title={k3?'93 层结构，可逐层选择':'逐层查看 Flash / Pro 的压缩策略'} note="层号为 1-based"/>{!k3&&<div className="lab-controls"><label>Checkpoint <select value={variant} onChange={e=>{setVariant(e.target.value);setSelected(0)}}><option value="flash">DeepSeek V4 Flash · 43 层</option><option value="pro">DeepSeek V4 Pro · 61 层</option></select></label></div>}<div className="layer-legend">{(k3?['KDA','MLA']:['SWA','C4','C128']).map(t=><span key={t}><i className={t.toLowerCase()}/>{t}</span>)}</div><div className="layer-grid">{Array.from({length:n},(_,i)=><button key={i} className={`layer-tile ${typeOf(i).toLowerCase()} ${i===ix?'selected':''}`} aria-label={`第 ${i+1} 层 ${typeOf(i)}`} aria-pressed={i===ix} onClick={()=>setSelected(i)}>{i+1}</button>)}</div><div className="layer-detail" aria-live="polite"><div><span className="eyebrow">LAYER {String(ix+1).padStart(2,'0')}</span><h4>{type}{!k3&&type!=='SWA'?' + SWA':''} <span>→</span> {k3&&ix===0?'Dense FFN':!k3&&ix<3?'Hash MoE':'MoE'}</h4><p>{k3?(type==='KDA'?'更新 short-conv 与 recurrent 状态，不存逐 token 的 full KV。':'访问不断增长的 576 维 latent cache；NoPE 仍保留 64 维历史命名分支。'):(type==='C4'?'细粒度压缩候选经 indexer 选择 top-k，并与近期 SWA 联合计算。':type==='C128'?'读取高压缩历史摘要，并保留近期 SWA 的细节。':'不创建压缩历史分支，使用滑动窗口。')}</p><p className="small muted">{k3?`AttnRes 配置 block size 12；当前层处于第 ${Math.floor(ix/12)+1} 个层分组。`:`主干层以外另有 1 个 MTP 层，compress_ratio=0，未计入上方 ${n} 层。`}</p></div><References refs={k3?['sg.k3#KimiK3DecoderLayer','vl.k3','config.kimi-k3']:['sg.v4#DeepseekV4DecoderLayer','vl.v4#DeepseekV4DecoderLayer',`config.deepseek-v4-${variant}`]} open={open} engine={engine}/></div></div>
}
function SparseLab(){
 const [length,setLength]=useState(8192),[ratio,setRatio]=useState(4),[topk,setTopk]=useState(512);
 const d=sparseDemo({length,ratio,topk});
 return <div className="lab"><Head label="SPARSE VISIBILITY LAB" title="在当前 query 边界，能看见多少历史" note="逻辑示意 · 非 learned score"/><div className="control-grid"><Range label="因果前缀（含当前 token）" min={1} max={65536} value={length} onChange={setLength}/><label className="control">精确输入长度<input type="number" min={1} max={65536} value={length} onChange={e=>setLength(Math.max(1,Math.min(65536,+e.target.value||1)))}/></label></div><div className="lab-controls"><label>当前层 <select value={ratio} onChange={e=>setRatio(+e.target.value)}><option value={4}>C4 + SWA</option><option value={128}>C128 + SWA</option><option value={0}>SWA only</option></select></label><label>模型 index_topk <select value={topk} onChange={e=>setTopk(+e.target.value)}><option value={512}>Flash · 512</option><option value={1024}>Pro · 1024</option></select></label></div><div className="sparse-lanes"><div><span>近期原始窗口</span><div className="sparse-track swa-track"><strong>{d.window} token</strong></div></div><div><span>已完成压缩历史</span><div className="sparse-track"><div className="compressed-fill" style={{width:ratio?`${Math.max(4,d.completed?d.selected/d.completed*100:0)}%`:'0%'}}/><strong>{d.selected} / {d.completed} 组被读取</strong></div></div><div><span>未完成分组</span><div className="sparse-track pending-track"><strong>{d.pending}{ratio?` / ${ratio}`:''} token · 保留 partial state</strong></div></div></div><div className="lab-foot" aria-live="polite">{ratio===4?`候选 ${d.completed} ≤ top-k ${topk} 时直接全选，否则只读 ${d.selected} 个候选。`:ratio===128?'C128 读取已完成的高压缩组，这里不应用 C4 的 top-k 上限。':'本层不走 compressor/indexer 分支。'} 分组数以 floor(L / ratio) 示意；真实重叠窗口、页映射、sink 与边界 padding 见源码。</div></div>
}
function SpecLab(){
 const [tokens,setTokens]=useState(4),[acceptance,setAcceptance]=useState(.8),[draft,setDraft]=useState(.12),[verify,setVerify]=useState(1.4);
 const d=speculativeEstimate({tokens,acceptance,draft,verify});
 return <div className="lab"><Head label="SPECULATION COST LAB" title="高接受率为什么仍可能不加速" note="独立同分布假设 · 非实测"/><div className="control-grid"><Range label="草拟 token 数 k" min={1} max={12} value={tokens} onChange={setTokens}/><Range label="每位置接受概率 a" min={0} max={1} step={.05} value={acceptance} onChange={setAcceptance}/><Range label="每个 draft 成本 / 普通 decode" min={.02} max={.5} step={.02} value={draft} onChange={setDraft}/><Range label="整次 verify 成本 / 普通 decode" min={1} max={5} step={.1} value={verify} onChange={setVerify}/></div><div className="metric-row" aria-live="polite"><div><span>期望推进</span><strong>{d.expected.toFixed(2)} <small>token / 轮</small></strong></div><div><span>每轮相对成本</span><strong>{d.cost.toFixed(2)} <small>decode 单位</small></strong></div><div><span>理想相对速度</span><strong className={d.speedup<1?'negative':''}>{d.speedup.toFixed(2)}×</strong></div></div><p className="small muted">E = 1 + a + a² + … + aᵏ；速度比 = E / (k·draft + verify)。假设含 1 个修正/bonus token、draft 串行、成本不随 batch 变化。真实接受概率相关，且还需计状态恢复、通信和调度成本。</p></div>
}
function ParallelLab(){const [axis,setAxis]=useState('TP');const descriptions:Record<string,[string,string,string]>={TP:['切矩阵 / heads','同一层的矩阵分片分到多个 rank，常在输出侧归约。','权重与计算分摊；层间 collective 增多。'],PP:['切模型深度','各 stage 执行连续层，hidden state 跨 stage 传递。','容量扩展；自回归小 batch 可能有 bubble。'],DP:['切请求 / batch','不同 rank 或 replica 处理不同请求。','服务吞吐扩展；权重与部分 cache 可能复制。'],EP:['切专家池','token 依路由被 dispatch 到持有目标专家的 rank。','专家容量扩大；网络与热点专家可能成为瓶颈。'],DCP:['切历史上下文','分摊 decode 历史 cache / attention，合并时保留 LSE。','减少单 rank 历史负担；增加 query/output 通信。']};return <div className="lab"><Head label="PARALLELISM EXPLORER" title="先选切分对象，再看通信代价"/><div className="segmented">{Object.keys(descriptions).map(k=><button key={k} aria-pressed={axis===k} onClick={()=>setAxis(k)}>{k}</button>)}</div><div className="rank-grid">{[0,1,2,3].map(i=><div key={i}><span>RANK {i}</span><strong>{axis==='TP'?`矩阵分片 ${i+1}/4`:axis==='PP'?`层阶段 ${i+1}/4`:axis==='DP'?`请求组 ${i+1}`:axis==='EP'?`专家集合 ${i+1}`:`历史分片 ${i+1}/4`}</strong><Database size={20}/></div>)}</div><div className="lab-foot" aria-live="polite"><strong>{descriptions[axis][0]}</strong> · {descriptions[axis][1]} {descriptions[axis][2]} 这是单轴示意，混合并行的组关系不能直接按所有 size 相乘。</div></div>}
const symptoms=[{name:'首 token 慢',chain:'排队 → 输入处理 → 前缀恢复 → prefill',refs:['sg.tokenizer','sg.scheduler','vl.async','vl.kv'],action:'分开观察 queue time、prompt 长度、encoder 时间和 cache restore；同流量下对照冷/热缓存。'}, {name:'后续 token 慢',chain:'batch 组成 → attention 读取 → MoE 通信 → 输出',refs:['sg.runner','vl.runner','vl.mla','vl.modularmoe'],action:'检查大 prefill 干扰、kernel/collective 时间和 batch bucket；不要只增大并发。'}, {name:'显存不足',chain:'权重 → KV / KDA state → graph → 临时峰值',refs:['sg.v4pool','vl.specs','vl.mambashape','vl.graph'],action:'分开记录启动加载峰值与 steady-state；K3 的每请求固定状态和 V4 的压缩 partial state 都要计入。'}, {name:'偶发结果错误',chain:'模板 → 量化 → slot mapping → 状态恢复',refs:['vl.k3parser','vl.kdametadata','vl.indexer','sg.v4state'],action:'复现 prefix hit、chunk 边界与 speculative rejection；对照 eager + 非投机路径以缩小触发范围。'}];
function Diagnosis({open,engine}:Props){const [i,setI]=useState(0),s=symptoms[i];return <div className="lab"><Head label="DIAGNOSIS PATH" title="从症状找到应该读的代码"/><div className="segmented">{symptoms.map((s,j)=><button key={s.name} aria-pressed={j===i} onClick={()=>setI(j)}>{s.name}</button>)}</div><div className="trace-detail" aria-live="polite"><GitBranch size={22}/><h4>{s.chain}</h4><p>{s.action}</p><References refs={s.refs} open={open} engine={engine}/></div></div>}
function Sources({open,engine}:Props){const [query,setQuery]=useState('');const files=Object.values(sourceIndex.files).filter(f=>(engine==='both'||f.repo===engine||f.repo==='config')&&(f.path+' '+f.id).toLowerCase().includes(query.toLowerCase()));return <div className="lab"><Head label="SOURCE LIBRARY" title="核心源码与回归测试" note={`${files.length} 个匹配文件`}/><label className="control">按文件名或路径搜索<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="如 kimi、scheduler、test、compress…"/></label><div className="source-library">{files.map(f=><button key={f.id} onClick={()=>open(f.id)}><span className={`repo-dot ${f.repo}`}/><span><strong>{f.path.split('/').at(-1)}</strong><small>{repoName(f.repo)} / {f.path}</small></span><span>{fmt(f.lineCount)} 行<ArrowRight size={14}/></span></button>)}</div>{!files.length&&<p>没有匹配文件。试试模型名或模块名。</p>}</div>}
export function Lab(p:Props){switch(p.kind){case'trace':return <Trace {...p}/>;case'scheduler':return <SchedulerLab/>;case'cache':return <RadixLab open={p.open}/>;case'cache-vllm':return <VllmCacheLab open={p.open}/>;case'memory':return <MemoryLab/>;case'layers-k3':case'layers-v4':return <LayersLab {...p}/>;case'sparse':return <SparseLab/>;case'speculation':return <SpecLab/>;case'parallel':return <ParallelLab/>;case'diagnosis':return <Diagnosis {...p}/>;case'sources':return <Sources {...p}/>;default:return null}}
