import {useState} from 'react';
import {ArrowRight,ChevronRight,Code2,Layers3,ArrowDown,Lightbulb} from 'lucide-react';
import {guideFor,detailsFor,topics,topicGroups,type View,type Topic} from './curriculum';
import {objectContracts} from './objectContracts';
import type {Framework} from './curriculumTypes';
import type {OpenCode} from './data';
import {resolveRef} from './data';
import {References} from './References';
import {Lab} from './Labs';
type Props={engine:Framework;topic:Topic;view:View;open:OpenCode;go:(topic:string,view?:View)=>void;theme:'light'|'dark';changeView:(view:View)=>void};
const groupNotes:Record<string,string>={'引擎主线':'先看谁做决定，再看谁执行。','状态与计算':'追踪缓存位置、历史可见性和专家工作。','模型实现':'把通用机制放回 K3 与 V4 的真实层结构。','运行与工程':'解释并行、迁移、验证与用户可见行为。'};
export function StudyPage({engine,topic,view,open,go,theme,changeView}:Props){
 const guide=guideFor(engine,topic.id),[selected,setSelected]=useState(0),node=guide.nodes[selected];
 const objects=objectContracts[`${engine}:${topic.id}`]??[],more=detailsFor(engine,topic.id);
 const lab=topic.id==='cache'&&engine==='vllm'?'cache-vllm':topic.lab;
 return <div className="study-content" role="tabpanel" id={`panel-${view}`} aria-labelledby={`tab-${view}`}>
 {view==='map'&&<>
  <section className="mechanism-map"><div className="study-section-title"><div><span className="eyebrow">01 / {guide.kind==='flow'?'MAIN PATH':'COMPONENTS'}</span><h2>{guide.kind==='flow'?'沿主干找到责任边界':'共同完成这项职责的组件'}</h2></div><span className="map-instruction">点击节点，查看输入与输出</span></div>
   <div className={`mechanism-nodes ${guide.kind}`} aria-label="本框架结构图">{guide.nodes.map((item,i)=><div className="mechanism-node-wrap" key={i}><button className={`mechanism-node ${i===selected?'selected':''}`} aria-pressed={i===selected} onClick={()=>setSelected(i)}><span className="mechanism-number">0{i+1}</span><h3>{item.title}</h3><code>{resolveRef(item.ref).symbol?.name??resolveRef(item.ref).file.path.split('/').at(-1)}</code><span className="mechanism-select">{i===selected?'正在查看':'查看职责'}<ChevronRight size={14}/></span></button>{i<guide.nodes.length-1&&guide.kind==='flow'&&<ArrowRight className="mechanism-edge" size={17}/>}</div>)}</div>
   <div className="mechanism-detail" aria-live="polite"><div><span className="eyebrow">SELECTED / 0{selected+1}</span><h3>{node.title}</h3><p>{node.detail}</p><References refs={[node.ref]} open={open} engine={engine}/></div><div className="io-stack"><div><span>输入</span><p>{node.input}</p></div><ArrowDown size={15}/><div><span>输出</span><p>{node.output}</p></div></div></div>
   <p className="diagram-scope">{guide.kind==='flow'?'图示聚焦本页主干，省略辅助分支；具体调用与条件见节点源码。':'组件按职责分组，位置不表示严格的调用先后。'}</p>
  </section>
  {topic.id==='overview'?<section className="reading-roadmap"><div className="study-section-title"><div><span className="eyebrow">02 / READING ROUTE</span><h2>按四个层次往下读</h2></div></div><div className="roadmap-grid">{topicGroups.map((group,i)=><div key={group}><span className="roadmap-number">0{i+1}</span><h3>{group}</h3><p>{groupNotes[group]}</p><div>{topics.filter(t=>t.group===group&&!t.parent&&t.id!=='overview').map(t=><button key={t.id} onClick={()=>go(t.id)}>{t.title}<ArrowRight size={13}/></button>)}</div></div>)}</div></section>:<div className="study-next-choices"><button onClick={()=>changeView('objects')}><Layers3 size={19}/><span><strong>接着看对象与接口</strong><small>{objects.length?`${objects.length} 个关键对象，逐项解释真实字段`:'用输入、输出与源码定位模块契约'}</small></span><ArrowRight size={17}/></button><button onClick={()=>changeView('design')}><Lightbulb size={19}/><span><strong>再理解设计取舍</strong><small>{guide.decisions[0].title}</small></span><ArrowRight size={17}/></button></div>}
 </>}
 {view==='flow'&&<section className="execution-walk"><div className="study-section-title"><div><span className="eyebrow">STEP BY STEP</span><h2>{guide.kind==='flow'?'一次工作如何跨过这些边界':'逐个理解组件怎样协作'}</h2></div><span className="map-instruction">{selected+1} / {guide.nodes.length}</span></div><div className="walk-layout"><div className="walk-stages" aria-label="执行步骤">{guide.nodes.map((item,i)=><button aria-pressed={i===selected} key={i} onClick={()=>setSelected(i)}><span>0{i+1}</span><strong>{item.title}</strong><ChevronRight size={15}/></button>)}</div><div className="walk-detail" aria-live="polite"><span className="eyebrow">STEP 0{selected+1}</span><h3>{node.title}</h3><p>{node.detail}</p><div className="handoff-pair"><div><span>这一阶段收到</span><strong>{node.input}</strong></div><ArrowRight size={18}/><div><span>交给后续的结果</span><strong>{node.output}</strong></div></div><References refs={[node.ref]} open={open} engine={engine}/><button className="button primary walk-next" disabled={selected===guide.nodes.length-1} onClick={()=>setSelected(selected+1)}>下一阶段<ArrowRight size={14}/></button></div></div>{topic.id==='cache'&&<button className="button walkthrough-link" onClick={()=>changeView('lab')}>用具体 token 和物理位置走一遍<ArrowRight size={15}/></button>}</section>}
 {view==='objects'&&<section className="objects-section"><div className="study-section-title"><div><span className="eyebrow">STATE & CONTRACTS</span><h2>{objects.length?'先分清对象，再读字段':'沿输入与输出确认模块边界'}</h2></div></div>{objects.map((object,i)=><details className="object-contract" key={object.ref} open={i===0}><summary><span><code>{object.name}</code><small>{object.role}</small></span><ChevronRight size={17}/></summary><div className="object-body"><div className="field-table">{object.fields.map(([field,meaning])=><div key={field}><code>{field}</code><p>{meaning}</p></div>)}</div><References refs={[object.ref]} open={open} engine={engine}/></div></details>)}<div className="interface-grid">{guide.nodes.map(item=><article key={item.title}><span className="eyebrow">接口边界</span><h3>{item.title}</h3><dl><div><dt>输入</dt><dd>{item.input}</dd></div><div><dt>输出</dt><dd>{item.output}</dd></div></dl><References refs={[item.ref]} open={open} engine={engine}/></article>)}</div></section>}
 {view==='design'&&<section className="design-section"><div className="study-section-title"><div><span className="eyebrow">WHY THIS DESIGN</span><h2>从约束理解选择</h2></div></div><div className="design-cards">{guide.decisions.map((decision,i)=><article key={decision.title}><span className="decision-index">0{i+1}</span><h3>{decision.title}</h3><div className="decision-reason"><span>设计原因</span><p>{decision.reason}</p></div><div className="decision-cost"><span>代价与边界</span><p>{decision.cost}</p></div></article>)}</div><References refs={[...new Set(guide.nodes.map(n=>n.ref))]} open={open} engine={engine}/>{more.length>0&&<div className="deep-details"><h3>按问题继续深挖</h3>{more.map(section=><details key={section.title}><summary>{section.title}<ChevronRight size={16}/></summary><div>{section.body.map((text,i)=><p key={i}>{text}</p>)}<div className="deep-principle"><b>设计原理</b><p>{section.principle}</p><b>代价与边界</b><p>{section.tradeoff}</p></div><References refs={section.refs} open={open} engine={engine}/></div></details>)}</div>}</section>}
 {view==='lab'&&lab&&<><div className="experiment-context"><Code2 size={16}/><p>{topic.id==='cache'?'沿真实数据结构观察具体案例。节点 ID、物理位置与时间顺序为教学示意。':'用简化输入探索机制和边界；模型数学示例可跨实现成立，源码入口始终属于当前框架。'}</p></div><Lab key={`${engine}:${topic.id}`} kind={lab} engine={engine} open={open} go={go} theme={theme}/></>}
 </div>
}
